export const wordPairsDefault = [
{ es: '¡Buen finde! ', ua: 'Гарних вихідних!', en:'Have a good weekend!' },
{ es: '¡Cuidado!', ua: 'Обережно!', en:'Watch out!' },
{ es: '¿De verdad? ', ua: 'Правда?', en:'Really?' },
{ es: 'a menudo', ua: 'часто', en:'often' },
{ es: 'a veces', ua: 'іноді', en:'sometimes' },
{ es: 'abundante', ua: 'рясний, ситний, наповнений', en:'abundant' },
{ es: 'acabar ', ua: 'закінчувати', en:'to end, to finish' },
{ es: 'además', ua: 'до того ж', en:'also' },
{ es: 'además', ua: 'крім того', en:'besides, also' },
{ es: 'admiración', ua: 'захоплення', en:'admiration' },
{ es: 'aduana', ua: 'митниця', en:'customs' },
{ es: 'afortunadamente', ua: 'на щастя', en:'fortunately' },
{ es: 'al cole', ua: 'в школу', en:'to school' },
{ es: 'alguien', ua: 'хтось, дехто', en:'someone' },
{ es: 'algún', ua: 'щось, дещо', en:'something' },
{ es: 'alrededor', ua: 'близько', en:'around (9 o`clock)' },
{ es: 'anoche = ayer en la noche', ua: 'минулої ночі', en:'Last night = yesterday night' },
{ es: 'anocheser', ua: 'вечоріти', en:'nightfall' },
{ es: 'anteayer', ua: 'позавчора', en:'the day before yesterday' },
{ es: 'asombrosamente', ua: 'дивовижно', en:'surprisingly' },
{ es: 'asombroso', ua: 'дивовижний', en:'amazing' },
{ es: 'aterrizar ', ua: 'приземлятися (на літаку)', en:'to land (by plane)' },
{ es: 'aunque', ua: 'хоча', en:'although' },
{ es: 'avergüenza', ua: 'збентежений', en:'ashamed, embarrassed' },
{ es: 'cocinar (con fuego)', ua: 'готувати (на плиті, на вогні)', en:'Cook (with fire)' },
{ es: 'comenzar', ua: 'починати', en:'begin' },
{ es: 'con los demás', ua: 'з іншими', en:'with the rest' },
{ es: 'contar ', ua: 'розповідати', en:'to tell, to count' },
{ es: 'cuando comenzó a llover', ua: 'коли почався дощ', en:'when it started to rain' },
{ es: 'cuando sonó el teléfono', ua: 'коли задзвонив телефон', en:'When the telephone rang' },
{ es: 'cuando tocaste a la puerta', ua: 'коли ти постукав у двері', en:'When you touched the door' },
{ es: 'cuento', ua: 'історія, оповідь', en:'tale' },
{ es: 'dar igual', ua: 'однаково, не важливо', en:'same, not important' },
{ es: 'dársena', ua: 'док для лодок', en:'dock' },
{ es: 'de antelación', ua: 'на перед', en:'in advance' },
{ es: 'de repente', ua: 'раптово', en:'all of a sudden' },
{ es: 'de vez en cuando', ua: 'час від часу', en:'from time to time' },
{ es: 'deberes', ua: 'домашня робота', en:'homework' },
{ es: 'demasiado', ua: 'забагато', en:'too much' },
{ es: 'deprisa', ua: 'швидко', en:'fast' },
{ es: 'despacio', ua: 'повільно', en:'slow' },
{ es: 'despegar', ua: 'злітати  (на літаку)', en:'take off  (by plane)' },
{ es: 'el que no llora no mama', ua: 'хто не просить, не отримає', en:'The one who does not cry does not mam' },
{ es: 'ella ya', ua: 'вона вже', en:'she already' },
{ es: 'en aquella época', ua: 'в той час', en:'at that time' },
{ es: 'encontrar', ua: 'знаходити', en:'find' },
{ es: 'encontrarse', ua: 'зустрічатися', en:'meet' },
{ es: 'enseñar', ua: 'навчати', en:'teach' },
{ es: 'entonces', ua: 'отже', en:'so/then' },
{ es: 'entonces', ua: 'тоді, отже', en:'so, then, now' },
{ es: 'equipaje', ua: 'багаж', en:'luggage' },
{ es: 'estaba a punto de', ua: 'я збирався', en:'I was about to' },
{ es: 'estupendo', ua: 'чудово', en:'great' },
{ es: 'facturación de equipajes', ua: 'реєстрація багажу', en:'luggage registration' },
{ es: 'fracaso', ua: 'невдача', en:'fail' },
{ es: 'graduarse', ua: 'випускатись', en:'to graduate' },
{ es: 'habitual', ua: 'звичайно, зазвичай', en:'usual' },
{ es: 'hace quince años', ua: '15 років тому', en:'fifteen years ago' },
{ es: 'hace un rato', ua: 'нещодавно', en:'a while ago' },
{ es: 'hasta el anochecer', ua: 'до ночі!', en:'until dusk' },
{ es: 'hojas', ua: 'листя', en:'leaves' },
{ es: 'honrado', ua: 'чесний, шанований', en:'hones, honored' },
{ es: 'irritación', ua: 'роздратування', en:'irritation' },
{ es: 'la hora punta', ua: 'час пік', en:'rush hour' },
{ es: 'ladrones', ua: 'крадії, злодії', en:'thieves' },
{ es: 'leyendas', ua: 'легенди', en:'Legends' },
{ es: 'ligero', ua: 'легко, ніжно, тонко', en:'light' },
{ es: 'llegadas', ua: 'прибуття', en:'arrivals' },
{ es: 'llegar', ua: 'прибувати, приходити', en:'arrive, reach, get to' },
{ es: 'llevar', ua: 'нести, носити(одяг)', en:'take, carry, wear' },
{ es: 'lo mismo', ua: 'так само', en:'same' },
{ es: 'lo peor', ua: 'найгірше', en:'worst' },
{ es: 'luego', ua: 'потім', en:'then' },
{ es: 'matrimonio', ua: 'одруження', en:'marriage' },
{ es: 'me da igual', ua: 'мені байдуже', en:'I don`t care' },
{ es: 'me llamaste', ua: 'ти дзвонив мені', en:'you called me' },
{ es: 'mientras', ua: 'поки', en:'while' },
{ es: 'mostrador', ua: 'стійка інформації', en:'counter (information)' },
{ es: 'mudarse', ua: 'переїзжати', en:'move house' },
{ es: 'no importa', ua: 'не важливо, ожнаково', en:'not important, don`t care' },
{ es: 'no me importa', ua: 'мені не важливо', en:'I don`t care' },
{ es: 'pasar', ua: 'проходити', en:'pass' },
{ es: 'pasear', ua: 'прогулюватись', en:'sightseeing' },
{ es: 'peor', ua: 'гірше', en:'worse' },
{ es: 'perdir', ua: 'втрачати, губити', en:'lose' },
{ es: 'pinchazo', ua: 'укол', en:'prick' },
{ es: 'por lo que', ua: 'отже', en:'через це' },
{ es: 'por supuesto', ua: 'авжеж', en:'of course' },
{ es: 'por un rato', ua: 'на деякий час', en:'for a while' },
{ es: 'preparar (ej. bocadillo)', ua: 'приготувати (з готових продуктів)', en:'Prepare (eg sandwiches)' },
{ es: 'profundo', ua: 'глибоко', en:'deep' },
{ es: 'pronto', ua: 'швидко, рано', en:'soon, early, quick' },
{ es: 'reír', ua: 'сміятись', en:'laugh' },
{ es: 'resuelto!', ua: 'вирішено!', en:'resolved!' },
{ es: 'retraso', ua: 'запізнення', en:'delay' },
{ es: 'sala de espera', ua: 'зал очікування', en:'waiting room' },
{ es: 'salvage', ua: 'дикий', en:'salvage' },
{ es: 'señalar', ua: 'помічати', en:'to mark, to note, to highlight' },
{ es: 'solicitar', ua: 'запитувати, робити запит', en:'to request' },
{ es: 'suele', ua: 'зазвичай', en:'usually' },
{ es: 'sueño', ua: 'сон, мрія', en:'dream' },
{ es: 'supongo', ua: 'я вважаю', en:'I guess' },
{ es: 'tanto', ua: 'багато', en:'so much' },
{ es: 'temprano', ua: 'рано', en:'early' },
{ es: 'tengo ganas de', ua: 'я почуваюсь як, хочу', en:'I want to' },
{ es: 'tengo la intención de', ua: 'маю намір, план', en:'I have the intention of' },
{ es: 'todo va bien', ua: 'Bce йде добре', en:'everything is going well' },
{ es: 'tonto(a)', ua: 'дурний', en:'stupid' },
{ es: 'trasladar', ua: 'рухатись, переїзджати', en:'move, translate, transfer' },
{ es: 'trayecto', ua: 'маршрут, подорож', en:'journey, course' },
{ es: 'un golpe', ua: 'удар', en:'a hit' },
{ es: 'ventaja', ua: 'перевага', en:'advantage' },
{ es: 'vergüenza', ua: 'сором', en:'shame' },
{ es: 'ya', ua: 'вже', en:'already(pasado)' },
{ es: 'amistad', ua: 'дружба', en:'friendship' },
{ es: 'matrcula de honor', ua: 'диплом про відзнаку', en:'Diploma' },
{ es: 'bruja ', ua: 'відьма', en:'witch' },
{ es: 'tumba', ua: 'могила', en:'grave' },
{ es: 'velatorio', ua: 'прощання з померлими', en:'' },
{ es: 'el coco', ua: 'бабай', en:'boogeyman' },
{ es: 'tanatorio', ua: 'місця прощання з померлими', en:'tanatorio' },
{ es: 'funaral', ua: 'похорон', en:'funeral' },
{ es: 'propina', ua: 'чайові', en:'tip' },
{ es: 'amanecer (la salida del sol)', ua: 'схід сонця', en:'sunrise (sunrise)' },
{ es: 'atardecer (la puesta del sol)', ua: 'захід сонця', en:'sunset (sunset)' },
{ es: 'sañalar', ua: 'помічати, позначати', en:'to mark' },
{ es: 'legumbres', ua: 'бобові', en:'legumes' },
{ es: 'rellenar', ua: 'наповнювати', en:'fill, refill' },
{ es: 'montar', ua: 'їхати верхи (велосипед, кінь)', en:'to ride' },
{ es: 'medir', ua: 'міряти', en:'measure' },
{ es: 'ajedes ', ua: 'шахи', en:'chess' },
{ es: 'mentira', ua: 'брехня', en:'lie' },
{ es: 'oler', ua: 'мати запах, пахнути', en:'to smell' },
{ es: 'hervir', ua: 'варити, кипʼятити', en:'to boil' },
{ es: 'soler (¿A qué hora sueles comer?)', ua: 'зазвичай щось робити', en:'to usually do' },
{ es: 'futin', ua: 'проходка, ходьба', en:'jogging' },
{ es: 'una cabezada', ua: 'денний сон', en:'nap' },
{ es: 'sanderismo', ua: 'піші походи', en:'hiking' },
{ es: 'montañismo, escalada', ua: 'альпінізм, скалолазіння', en:'climbing' },
{ es: 'soldador (soldar)', ua: 'зварюваьлник (зварювати)', en:'welder (to weld)' },
{ es: 'la terminacion', ua: 'закінчення', en:'the ending' },
{ es: 'prometer', ua: 'обіцяти', en:'promise, pledge' },
{ es: 'orar', ua: 'молитися', en:'to pray' },
{ es: 'aprovechan', ua: 'користуючись нагодою', en:'they take advantage' },
{ es: 'consagrar', ua: 'освячувати', en:'consecrated, blessed' },
{ es: 'estrictamente', ua: 'строго', en:'strictly' },
{ es: 'vínculo familiar', ua: 'сімейний зв`язок', en:'family relation (bond)' },
{ es: 'varicela', ua: 'вітрянка', en:'chickenpox' },
{ es: 'asqueroso', ua: 'огидний, бридкий', en:'disgusting' },
{ es: 'estar en paro', ua: 'бути безробітним', en:'be unemployed' },
{ es: 'cachorro', ua: 'цуценя, щеня', en:'puppy' },
{ es: 'estar quemado', ua: 'бути вигорівшим', en:'to be burnt out' },
{ es: 'enganchar', ua: 'підсідати, зачепити', en:'to hook ' },
{ es: 'disfraz', ua: 'костюм', en:'costume, fancy dress' },
{ es: 'pisadas (pisar)', ua: 'сліди ніг', en:'footprints' },
{ es: 'pasos', ua: 'корки', en:'steps' },
{ es: 'ruidos extraños', ua: 'дивні звуки', en:'strange noises' },
{ es: 'natilla', ua: 'заварний крем', en:'custard, cream' },
{ es: 'microondas', ua: 'мікрохвильовка', en:'microwave' },
{ es: 'desván', ua: 'чердка', en:'attic, loft, garret' },
{ es: 'sellos', ua: 'марки', en:'post selas' },
{ es: 'fíjate', ua: 'зверни увагу, Дивись!', en:'Imagine! Just look!' },
{ es: 'retrato', ua: 'портрет', en:'portrait' },
{ es: 'paloma', ua: 'голуб', en:'pigeon' },
{ es: 'qué sucede (suceder)', ua: 'що відбуваєть', en:'what`s going on' },
{ es: 'revista', ua: 'журнал', en:'magazine, journal' },
{ es: 'estuche', ua: 'чохол, пенал, контейнер', en:'case, box, container' },
{ es: 'traviezo', ua: 'шкодний, неслухняний', en:'traviezo, badly behaved' },
{ es: 'castigar', ua: 'карати, наказувати', en:'to punish, penalize' },
{ es: 'astucia', ua: 'хитрий, винахідливий', en:'cunning, tricky, crafty' },
{ es: 'arado', ua: 'плуг', en:'plow (agriculture)' },
{ es: 'herrero', ua: 'коваль', en:'blacksmith, hammerman' },
{ es: 'bollo relleno al vapor', ua: 'булочка з начинкою на пару', en:'steamed stuffed bun' },
{ es: 'amasar', ua: 'замішувати (тісто)', en:'knead, mash, pug' },
{ es: 'títeres', ua: 'ляльковий театр', en:'puppetry, doll teatre' },
{ es: 'convocar', ua: 'скликати', en:'convene, call, summon' },
{ es: 'matanza', ua: 'забій', en:'slaughter, killing, massacre' },
{ es: 'nadie', ua: 'ніхто', en:'nobody, no one' },
{ es: 'murmurar', ua: 'бурчати', en:'murmur, mutter, babble' },
{ es: 'sacerdote', ua: 'священик', en:'priest, churchman' },
{ es: 'despoblarse', ua: 'знелюдніти', en:'depopulate' },
{ es: 'extraescolares', ua: 'позашкільний, кружок', en:'extracurricular' },
{ es: 'apodo', ua: 'псевдонім, кличка', en:'nickname' },
{ es: 'pelear', ua: 'битися', en:'fight' },
{ es: 'molestar', ua: 'дратувати, заважати', en:'annoy, disturb, bother' },
{ es: 'portarse', ua: 'поводитися', en:'behave' },
{ es: 'esquina', ua: 'кут', en:'corner' },
{ es: 'convivir', ua: 'співжити, співіснувати', en:'coexist, live together' },
{ es: 'fuertemente', ua: 'сильно', en:'strongly, heavily' },
{ es: 'alrededores', ua: 'оточення', en:'surroundings, environs' },
{ es: 'huelga', ua: 'страйк, забастовка', en:'strike, walkout' },
{ es: 'ser listo', ua: 'бути розумним', en:'be smart' },
{ es: 'estar listos', ua: 'бути готовим', en:'be ready' },
{ es: 'estar listo, preparado', ua: 'будь готовий', en:'be prepared' },
{ es: 'acontecimintos', ua: 'події', en:'events' },
{ es: 'cierto(a)', ua: 'певний', en:'certain' },
{ es: 'infancia', ua: 'дитинство', en:'childhood' },
{ es: 'escondite', ua: 'схованка', en:'hiding place' },
{ es: 'aficiones', ua: 'хобі', en:'hobbies' },
{ es: 'juguetes', ua: 'іграшки', en:'toys' },
{ es: 'con los demás', ua: 'з іншими', en:'with the rest' },
{ es: 'persigir', ua: 'переслідувати', en:'pursue' },
{ es: 'morder', ua: 'кусати', en:'bite' },
{ es: 'timidez', ua: 'сором`язливість', en:'shyness' },
{ es: 'le doy pena', ua: 'жаліти', en:'fell sorry' },
{ es: 'superficie', ua: 'поверхня, зона', en:'surface, area' },
{ es: 'amplia', ua: 'широкий', en:'wide' },
{ es: 'entorno', ua: 'навколо', en:'around' },
{ es: 'alejados', ua: 'віддалений', en:'remote' },
{ es: 'regatear', ua: 'торгуватися', en:'bargain' },
{ es: 'consejo', ua: 'порада', en:'advice' },
{ es: 'acuerdo', ua: 'Угода', en:'agreement' },
{ es: 'propietario, dueño, casero', ua: 'власник', en:'owner' },
{ es: 'equivoca', ua: 'неправильний', en:'wrong' },
{ es: 'equivocarse', ua: 'помилятися', en:'make a mistake' },
{ es: 'tormenta', ua: 'штурм', en:'storm' },
{ es: 'torpe', ua: 'росторопний, дурний', en:'clumsy' },
{ es: 'adelgazó un montón', ua: 'Він багато втратив', en:'He lost a lot' },
{ es: 'pedir un aumento', ua: 'просити підвищення', en:'ask for a raise' },
{ es: 'valer la pena', ua: 'того варте', en:'worth it' },
{ es: 'valiente', ua: 'хоробрий', en:'brave' },
{ es: 'pata de conejo', ua: 'Кроляча нога', en:'Rabbit leg' },
{ es: 'herradura', ua: 'підкова', en:'horseshoe' },
{ es: 'vela ', ua: 'свічка', en:'candle' },
{ es: 'supersticiones', ua: 'Забобони', en:'Superstitions' },
{ es: 'estrellarse', ua: 'тире', en:'dash' },
{ es: 'novato', ua: 'новачок', en:'rookie' },
{ es: 'sincero', ua: 'щирий', en:'sincere' },
{ es: 'grosero', ua: 'грубий', en:'rude' },
{ es: 'modesto', ua: 'скромний', en:'modest' },
{ es: 'precavido', ua: 'обережний', en:'cautious' },
{ es: 'cotillear', ua: 'плітка', en:'gossip' },
{ es: 'hipocrita', ua: 'лицемір', en:'hypocrite' },
{ es: 'perezoso', ua: 'ледачий', en:'lazy' },
{ es: 'agotado', ua: 'виснажений', en:'exhausted' },
{ es: 'herido', ua: 'поранений', en:'injured' },
{ es: 'aterrorizado', ua: 'жахливий', en:'terrified' },
{ es: 'estar asustad', ua: 'Бути наляканим', en:'Be scared' },
{ es: 'encender', ua: 'вмикати, світити', en:'turn on, light' },
{ es: 'vete!', ua: 'йди геть!', en:'go away!' },
{ es: 'despedir', ua: 'звільнити', en:'dismiss' },
{ es: 'mentiras blancas', ua: 'праведна брехня', en:'White Lies' },
{ es: 'exprimidor', ua: 'стиснення, соковитискач', en:'squeezer' },
{ es: 'colador', ua: 'ситечко', en:'strainer' },
{ es: 'cascanueces', ua: 'горіх, горіхолам', en:'nutcracker' },
{ es: 'buho', ua: 'сова', en:'owl' },
{ es: 'espantapajaros', ua: 'Опудало', en:'scarecrow' },
{ es: 'sordomudo', ua: 'глухий', en:'deaf -mute' },
{ es: 'Ojalá!', ua: 'Сподіваємось!', en:'Hopefully!' },
{ es: 'la beca', ua: 'стипендія', en:'scholarship' },
{ es: 'estiercol', ua: 'гній', en:'manure' },
{ es: 'fertilizante', ua: 'добриво', en:'fertilizer' },
{ es: 'brindis', ua: 'тост', en:'toast' },
{ es: '¡enhorabuena!', ua: 'Вітаємо!', en:'Congratulations!' },
{ es: 'fastidia', ua: 'дратівливий', en:'annoying' },
{ es: 'huir', ua: 'тікати', en:'flee' },
{ es: 'narrar', ua: 'розповідати', en:'narrate' },
  ]
  