const uaWord = document.querySelector('#uaWord');
const esWord = document.querySelector('#esWord');
const uaButton = document.querySelector('#ua');
const esButton = document.querySelector('#es');
const stopButton = document.querySelector('#stop');
const upperBox = document.querySelector('#upperBox');
const lowerBox = document.querySelector('#lowerBox');

const adjButton = document.querySelector('#adj');
const verbButton = document.querySelector('#verb');
const twoFiftyButton = document.querySelector('#twoFifty');
const thousandButton = document.querySelector('#thousand');

let wordSet = undefined;


adjButton.addEventListener('click', () => {
    wordSet = wordPairsAdj;
    uaButton.classList.remove('btn-grad-en');
    uaButton.classList.add('btn-grad');
    uaButton.innerText = 'UA 🇺🇦';
    esWord.textContent = '?'
    uaWord.textContent = '?'
})

verbButton.addEventListener('click', () => {
    wordSet = wordPairsVerbos;
    uaButton.classList.remove('btn-grad-en');
    uaButton.classList.add('btn-grad');
    uaButton.innerText = 'UA 🇺🇦';
    esWord.textContent = '?'
    uaWord.textContent = '?'
})

twoFiftyButton.addEventListener('click', () => {
    wordSet = wordPairs250;
    uaButton.innerText = 'EN 🇬🇧';
    uaButton.classList.remove('btn-grad');
    uaButton.classList.add('btn-grad-en');
    esWord.textContent = '?'
    uaWord.textContent = '?'
})

thousandButton.addEventListener('click', () => {
    uaButton.classList.remove('btn-grad');
    uaButton.classList.add('btn-grad-en');
    uaButton.innerText = 'EN 🇬🇧';
    wordSet = wordPairs1000;
    esWord.textContent = '?'
    uaWord.textContent = '?'
})

uaButton.addEventListener('click', () => {
    if (wordSet === undefined) {
        alert('Choose your words set')
    } else {
        newUaWord()
    }
})

esButton.addEventListener('click', () => {
    if (wordSet === undefined) {
        alert('Choose your words set')
    } else {
        newEsWord()
    }
})

function newUaWord() {
    let randomNumber = Math.floor(Math.random() * wordSet.length)
    uaWord.textContent = wordSet[randomNumber].ua
    esWord.textContent = '?'
    lowerBox.addEventListener('click', () => {
        esWord.textContent = wordSet[randomNumber].es
    }, { once: true })
}

function newEsWord() {
    let randomNumber = Math.floor(Math.random() * wordSet.length)
    esWord.textContent = wordSet[randomNumber].es
    uaWord.textContent = '?'
    upperBox.addEventListener('click', () => {
        uaWord.textContent = wordSet[randomNumber].ua
    }, { once: true })
}

const wordPairsVerbos = [
    { es: 'acompañar', ua: 'проводити/супроводжувати' },
    { es: 'almorzar', ua: 'обідати' },
    { es: 'ayudar', ua: 'допомагаті' },
    { es: 'bailar', ua: 'танцюваті' },
    { es: 'bañar', ua: 'купати' },
    { es: 'beber', ua: 'пити' },
    { es: 'cantar', ua: 'співати' },
    { es: 'calmar ', ua: 'заспокоювати' },
    { es: 'comer', ua: 'їсти' },
    { es: 'comprar', ua: 'купувати' },
    { es: 'conoser', ua: 'знати когось/зайомитись/узнавати' },
    { es: 'contestar', ua: 'відповидати' },
    { es: 'dar ', ua: 'давати' },
    { es: 'deber', ua: 'бути винним (жорстко)' },
    { es: 'decir', ua: 'говорити, розповідати' },
    { es: 'depender', ua: 'залежати' },
    { es: 'desayunar', ua: 'снідати' },
    { es: 'descansar', ua: 'відпочівати' },
    { es: 'dormir', ua: 'спати' },
    { es: 'enrojecer', ua: 'червоніти (сромитись)' },
    { es: 'enseñar', ua: 'викладати/навчати' },
    { es: 'escoger', ua: 'вибирати' },
    { es: 'escuchar ', ua: 'слухати' },
    { es: 'estar', ua: 'бути (фізично десь, в певному стані)' },
    { es: 'estudiar', ua: 'вчити' },
    { es: 'ganar', ua: 'заробляти/вигравати' },
    { es: 'gustar', ua: 'подобатась' },
    { es: 'hablar', ua: 'розмовляти' },
    { es: 'hacer', ua: 'робити' },
    { es: 'interesar', ua: 'цікавитись' },
    { es: 'interpretar un papel', ua: 'грати роль' },
    { es: 'ir', ua: 'йти' },
    { es: 'jugar', ua: 'грати в ігри' },
    { es: 'lavar', ua: 'мити' },
    { es: 'llamar', ua: 'називати' },
    { es: 'mirar', ua: 'дивитись' },
    { es: 'nadar', ua: 'плавати' },
    { es: 'necesitar', ua: 'потребувати' },
    { es: 'oír ', ua: 'чути' },
    { es: 'olvidar', ua: 'забувати' },
    { es: 'pagar ', ua: 'платити' },
    { es: 'pasar', ua: 'проводити час/траплятись' },
    { es: 'pasear', ua: 'гуляти' },
    { es: 'preguntar', ua: 'запитувати' },
    { es: 'pensar', ua: 'думати' },
    { es: 'poder', ua: 'могти/мати можливість' },
    { es: 'probar', ua: 'пробувати' },
    { es: 'prometer', ua: 'обіцяти' },
    { es: 'querer', ua: 'хотіти/любити' },
    { es: 'regalar', ua: 'дарувати' },
    { es: 'saber', ua: 'знати' },
    { es: 'ser', ua: 'бути' },
    { es: 'ser amigos', ua: 'бути друзями/дружити' },
    { es: 'tener', ua: 'мати' },
    { es: 'tener miedo', ua: 'боятись/мати страх' },
    { es: 'tomar', ua: 'брати/мати' },
    { es: 'trabajar', ua: 'працювати' },
    { es: 'tranquilizar', ua: 'заспокоювати' },
    { es: 'traducir', ua: 'перекладати' },
    { es: 'tratar', ua: 'старатись' },
    { es: 'vender', ua: 'продавати' },
    { es: 'venir', ua: 'приходити/приїзжати' },
    { es: 'ver', ua: 'бачити' },
    { es: 'viajar', ua: 'мандрувати' },
    { es: 'vivir', ua: 'жити' }
]

const wordPairsAdj = [
    { es: 'alto', ua: 'високий' },
    { es: 'delgado', ua: 'тонкий' },
    { es: 'flaco', ua: 'худий' },
    { es: 'joven', ua: 'молодий' },
    { es: 'moreno', ua: 'смуглий' },
    { es: 'rico (ser)', ua: 'багатий' },
    { es: 'rico (estar)', ua: 'смачний' },
    { es: 'fuerte', ua: 'сильний' },
    { es: 'amable', ua: 'дружній' },
    { es: 'educado', ua: 'ввічливий' },
    { es: 'simpático', ua: 'співчутливий' },
    { es: 'bueno', ua: 'хороший' },
    { es: 'bajo', ua: 'низький' },
    { es: 'gordo', ua: 'товстий' },
    { es: 'viejo', ua: 'старий' },
    { es: 'mayor', ua: 'дорослий' },
    { es: 'rubio', ua: 'блондин' },
    { es: 'pobre', ua: 'бідний' },
    { es: 'débil', ua: 'слабкий' },
    { es: 'grosero', ua: 'грубий' },
    { es: 'maleducado', ua: 'невихований' },
    { es: 'antipático', ua: 'недружній' },
    { es: 'malo', ua: 'поганий' },
    { es: 'fácil', ua: 'легкий' },
    { es: 'bonito', ua: 'гарний' },
    { es: 'hermoso', ua: 'чарівний' },
    { es: 'antiguo', ua: 'давній' },
    { es: 'nuevo', ua: 'новий' },
    { es: 'corto', ua: 'короткий' },
    { es: 'estrecho', ua: 'вузький' },
    { es: 'grande', ua: 'великий' },
    { es: 'divertido', ua: 'веселий' },
    { es: 'caro', ua: 'дорогий' },
    { es: 'difícil', ua: 'складний' },
    { es: 'feo', ua: 'некрасивий' },
    { es: 'horrible', ua: 'жахливий' },
    { es: 'moderno', ua: 'сучасний' },
    { es: 'viejo', ua: 'старий' },
    { es: 'largo', ua: 'довгий' },
    { es: 'ancho', ua: 'широкий' },
    { es: 'pequeño', ua: 'маленький' },
    { es: 'aburrido', ua: 'нудний' },
    { es: 'barato', ua: 'дешевий' },
    { es: 'triste', ua: 'сумний' },
    { es: 'enfadado', ua: 'злий' },
    { es: 'mal', ua: 'поланий' },
    { es: 'enfermo', ua: 'хворий' },
    { es: 'nervioso', ua: 'нервовий' },
    { es: 'preocupado', ua: 'стурбований' },
    { es: 'ocupado', ua: 'зайнятий' },
    { es: 'feliz', ua: 'щасливий' },
    { es: 'contento', ua: 'радісний' },
    { es: 'bien', ua: 'добре' },
    { es: 'sano', ua: 'здоровий' },
    { es: 'tranquilo', ua: 'спокійний' },
    { es: 'calmado', ua: 'заспокоєний' },
    { es: 'libre', ua: 'вільний' },
    { es: 'frío', ua: 'холодний' },
    { es: 'sucio', ua: 'брудний' },
    { es: 'encendido', ua: 'увімкнений' },
    { es: 'lleno', ua: 'повний' },
    { es: 'abierto', ua: 'відкритий' },
    { es: 'seco', ua: 'сухий' },
    { es: 'caliente', ua: 'гарячий' },
    { es: 'limpio', ua: 'чистий' },
    { es: 'apagado', ua: 'вимкнений' },
    { es: 'vacío', ua: 'порожній' },
    { es: 'cerrado', ua: 'закритий' },
    { es: 'mojado', ua: 'мокрий' }
]

const wordPairs250 = [
    { es: 'el,la', ua: 'the' },
    { es: 'de', ua: 'of, from' },
    { es: 'que', ua: 'that, which' },
    { es: 'y', ua: 'and' },
    { es: 'a', ua: 'to, at' },
    { es: 'en', ua: 'in, on' },
    { es: 'un', ua: 'a, an' },
    { es: 'ser', ua: 'to be' },
    { es: 'se', ua: 'reflexive marker' },
    { es: 'no', ua: 'no' },
    { es: 'haber', ua: 'to have' },
    { es: 'por', ua: 'by, for, through' },
    { es: 'con', ua: 'with' },
    { es: 'su', ua: 'his/her/their/your' },
    { es: 'para', ua: 'for, to, in order to' },
    { es: 'como', ua: 'like, as' },
    { es: 'estar', ua: 'to be (location)' },
    { es: 'tener', ua: 'to have' },
    { es: 'le', ua: 'he /she/it; 3rd person indirect obj' },
    { es: 'lo', ua: 'it; the (+ neuter)' },
    { es: 'lo', ua: 'it; 3rd person direct object (masc)' },
    { es: 'todo', ua: 'all, every' },
    { es: 'pero', ua: 'but, yet, except' },
    { es: 'más', ua: 'more' },
    { es: 'hacer', ua: 'to do, make' },
    { es: 'o', ua: 'or' },
    { es: 'poder', ua: 'to be able to; can' },
    { es: 'decir', ua: 'to tell, say' },
    { es: 'este', ua: 'this (m) [esta (f)]' },
    { es: 'ir', ua: 'to go' },
    { es: 'otro', ua: 'other, another' },
    { es: 'ese', ua: 'that (m) [esa (f)]' },
    { es: 'la', ua: 'it; 3rd person direct object (fem)' },
    { es: 'si', ua: 'if, whether' },
    { es: 'me', ua: 'me' },
    { es: 'ya', ua: 'already, still' },
    { es: 'ver', ua: 'to see' },
    { es: 'porque', ua: 'because' },
    { es: 'dar', ua: 'to give' },
    { es: 'cuando', ua: 'when' },
    { es: 'él', ua: 'he,' },
    { es: 'muy', ua: 'very, really' },
    { es: 'sin', ua: 'without' },
    { es: 'vez', ua: 'time (specific occurrence)' },
    { es: 'mucho', ua: 'much, many, a lot' },
    { es: 'saber', ua: 'to know (a fact), find out' },
    { es: 'qué', ua: 'what?, which?, how?' },
    { es: 'sobre', ua: 'on top of, over, about' },
    { es: 'mi', ua: 'my' },
    { es: 'alguno', ua: 'some, someone' },
    { es: 'mismo', ua: 'same' },
    { es: 'yo', ua: 'I' },
    { es: 'también', ua: 'also' },
    { es: 'hasta', ua: 'until, up to, even' },
    { es: 'año', ua: 'year' },
    { es: 'dos', ua: 'two' },
    { es: 'querer', ua: 'to want, love' },
    { es: 'entre', ua: 'between, among' },
    { es: 'así', ua: 'like that' },
    { es: 'primero', ua: 'first' },
    { es: 'desde', ua: 'from, since' },
    { es: 'grande', ua: 'large, great, big' },
    { es: 'eso', ua: 'that' },
    { es: 'ni', ua: 'not even, neither, nor' },
    { es: 'nos', ua: 'us' },
    { es: 'llegar', ua: 'to arrive' },
    { es: 'pasar', ua: 'to pass, spend (time)' },
    { es: 'tiempo', ua: 'time (general), weather' },
    { es: 'ella', ua: 'she,' },
    { es: 'sí', ua: 'yes' },
    { es: 'día', ua: 'day' },
    { es: 'uno', ua: 'one' },
    { es: 'bien', ua: 'well' },
    { es: 'poco', ua: 'little, few, a little bit' },
    { es: 'deber', ua: 'should, ought to; to owe' },
    { es: 'entonces', ua: 'so, then' },
    { es: 'poner', ua: 'to put (on), get' },
    { es: 'cosa', ua: 'thing' },
    { es: 'tanto', ua: 'so much, so many' },
    { es: 'hombre', ua: 'man, mankind, husband' },
    { es: 'parecer', ua: 'to seem, look like' },
    { es: 'nuestro', ua: 'our' },
    { es: 'tan', ua: 'such, as, too, so' },
    { es: 'donde', ua: 'where' },
    { es: 'ahora', ua: 'now' },
    { es: 'parte', ua: 'part, portion' },
    { es: 'después', ua: 'after' },
    { es: 'vida', ua: 'life' },
    { es: 'quedar', ua: 'to remain, stay' },
    { es: 'siempre', ua: 'always, forever' },
    { es: 'creer', ua: 'to believe, think' },
    { es: 'hablar', ua: 'to speak, talk' },
    { es: 'llevar', ua: 'to take, carry' },
    { es: 'dejar', ua: 'to let, leave' },
    { es: 'nada', ua: 'nothing, not at all' },
    { es: 'cada', ua: 'each, every' },
    { es: 'seguir', ua: 'to follow, keep on' },
    { es: 'menos', ua: 'less, fewer' },
    { es: 'nuevo', ua: 'new' },
    { es: 'encontrar', ua: 'to find' },
    { es: 'algo', ua: 'something, somewhat' },
    { es: 'sólo', ua: 'only, just' },
    { es: 'pues', ua: 'then, well then' },
    { es: 'llamar', ua: 'to call, name' },
    { es: 'venir', ua: 'to come' },
    { es: 'pensar', ua: 'to think' },
    { es: 'aquel', ua: 'that (over there)' },
    { es: 'momento', ua: 'moment, time' },
    { es: 'sino', ua: 'but, except, rather' },
    { es: 'esto', ua: 'this' },
    { es: 'salir', ua: 'to leave, go out' },
    { es: 'volver', ua: 'to return, to to do again' },
    { es: 'forma', ua: 'form, shape, way' },
    { es: 'antes', ua: 'before' },
    { es: 'bueno', ua: 'good' },
    { es: 'casa', ua: 'house' },
    { es: 'aunque', ua: 'although, even though' },
    { es: 'mundo', ua: 'world' },
    { es: 'tres', ua: 'three' },
    { es: 'tal', ua: 'such (a)' },
    { es: 'mejor', ua: 'best, better' },
    { es: 'tomar', ua: 'to take, drink' },
    { es: 'cierto', ua: 'certain, sure' },
    { es: 'conocer', ua: 'to know (someone or place)' },
    { es: 'hacia', ua: 'toward, towards' },
    { es: 'cómo', ua: 'how?' },
    { es: 'mujer', ua: 'woman, wife' },
    { es: 'vivir', ua: 'to live' },
    { es: 'aquí', ua: 'here' },
    { es: 'caso', ua: 'case, occasion' },
    { es: 'sentir', ua: 'to feel, regret' },
    { es: 'luego', ua: 'later, afterwards' },
    { es: 'país', ua: 'country' },
    { es: 'tratar', ua: 'to try, treat, deal with' },
    { es: 'lugar', ua: 'place, position' },
    { es: 'te', ua: 'you' },
    { es: 'persona', ua: 'person' },
    { es: 'mayor', ua: 'larger, older, main' },
    { es: 'último', ua: 'last, final' },
    { es: 'propio', ua: 'own, proper, typical' },
    { es: 'quien', ua: 'who, whom' },
    { es: 'mirar', ua: 'to look, watch' },
    { es: 'hora', ua: 'hour, time (specific)' },
    { es: 'ninguno', ua: 'no, none, nobody' },
    { es: 'trabajo', ua: 'work, job, effort' },
    { es: 'casi', ua: 'almost, nearly' },
    { es: 'punto', ua: 'point, dot, period' },
    { es: 'durante', ua: 'during, for (time)' },
    { es: 'cualquier', ua: 'any, anyone' },
    { es: 'mano', ua: 'hand' },
    { es: 'nunca', ua: 'never, ever' },
    { es: 'manera', ua: 'way, manner' },
    { es: 'cual', ua: 'which, who, whom' },
    { es: 'mientras', ua: 'while, whereas,' },
    { es: 'contar', ua: 'to tell, count' },
    { es: 'fin', ua: 'end' },
    { es: 'tipo', ua: 'type, kind' },
    { es: 'gente', ua: 'people' },
    { es: 'además', ua: 'also, as well, besides' },
    { es: 'solo', ua: 'lonely, alone' },
    { es: 'empezar', ua: 'to begin, start' },
    { es: 'ejemplo', ua: 'example' },
    { es: 'esperar', ua: 'to wait, hope (for), expect' },
    { es: 'hoy', ua: 'today, nowadays' },
    { es: 'lado', ua: 'side' },
    { es: 'hijo', ua: 'son, [pl] children' },
    { es: 'allí', ua: 'there, over there' },
    { es: 'éste', ua: 'this one' },
    { es: 'problema', ua: 'problem' },
    { es: 'cuenta', ua: 'bill, account' },
    { es: 'medio', ua: 'means, middle; pormedio: through' },
    { es: 'contra', ua: 'against, opposite' },
    { es: 'buscar', ua: 'to look for' },
    { es: 'dentro', ua: 'inside' },
    { es: 'largo', ua: 'long' },
    { es: 'palabra', ua: 'word' },
    { es: 'existir', ua: 'to exist' },
    { es: 'niño', ua: 'child, little boy' },
    { es: 'entrar', ua: 'to enter' },
    { es: 'embargo', ua: 'sin embargo: nevertheless' },
    { es: 'único', ua: 'only, unique, sole' },
    { es: 'padre', ua: 'father' },
    { es: 'trabajar', ua: 'to work' },
    { es: 'pequeño', ua: 'little, small, young' },
    { es: 'alto', ua: 'tall, high' },
    { es: 'cambio', ua: 'change' },
    { es: 'escribir', ua: 'to write' },
    { es: 'cuatro', ua: 'four' },
    { es: 'ahí', ua: 'there' },
    { es: 'perder', ua: 'to lose, miss' },
    { es: 'nosotros', ua: 'we' },
    { es: 'historia', ua: 'history, story' },
    { es: 'idea', ua: 'idea' },
    { es: 'agua', ua: 'water' },
    { es: 'producir', ua: 'to produce, cause' },
    { es: 'noche', ua: 'night, evening' },
    { es: 'ciudad', ua: 'city' },
    { es: 'modo', ua: 'way, manner' },
    { es: 'nombre', ua: 'name, noun' },
    { es: 'ocurrir', ua: 'to happen, occur' },
    { es: 'familia', ua: 'family' },
    { es: 'realidad', ua: 'reality, actuality' },
    { es: 'entender', ua: 'to understand' },
    { es: 'pedir', ua: 'to ask for, request' },
    { es: 'recibir', ua: 'to receive' },
    { es: 'obra', ua: 'work, book, deed' },
    { es: 'importante', ua: 'important' },
    { es: 'medio', ua: 'half, middle' },
    { es: 'verdad', ua: 'truth' },
    { es: 'mes', ua: 'month' },
    { es: 'todavía', ua: 'still, yet' },
    { es: 'razón', ua: 'reason; tener razón: to be right' },
    { es: 'cuanto', ua: 'en cuanto a: in terms of, regarding' },
    { es: 'bajo', ua: 'under, underneath' },
    { es: 'recordar', ua: 'to remember, remind' },
    { es: 'grupo', ua: 'group' },
    { es: 'mil', ua: 'thousand' },
    { es: 'humano', ua: 'human' },
    { es: 'terminar', ua: 'to finish, end' },
    { es: 'permitir', ua: 'to allow, permit' },
    { es: 'aparecer', ua: 'to appear' },
    { es: 'conseguir', ua: 'to get, acquire, obtain' },
    { es: 'comenzar', ua: 'to begin, start' },
    { es: 'varios', ua: 'several, various' },
    { es: 'posible', ua: 'possible' },
    { es: 'servir', ua: 'to serve' },
    { es: 'general', ua: 'general' },
    { es: 'sacar', ua: 'to take out' },
    { es: 'necesitar', ua: 'to need' },
    { es: 'relación', ua: 'relationship, relation' },
    { es: 'cinco', ua: 'five' },
    { es: 'cuerpo', ua: 'body' },
    { es: 'nadie', ua: 'nobody, anybody' },
    { es: 'mantener', ua: 'to keep, maintain' },
    { es: 'hecho', ua: 'fact, happening' },
    { es: 'ante', ua: 'before,' },
    { es: 'principio', ua: 'beginning, principle' },
    { es: 'resultar', ua: 'to result, turn out' },
    { es: 'igual', ua: 'equal, same (as)' },
    { es: 'señor', ua: 'sir, Mr, lord' },
    { es: 'pueblo', ua: 'people, village' },
    { es: 'tarde', ua: 'afternoon, evening' },
    { es: 'segundo', ua: 'second' },
    { es: 'leer', ua: 'to read' },
    { es: 'caer', ua: 'to fall' },
    { es: 'cambiar', ua: 'to change' },
    { es: 'ojo', ua: 'eye' },
    { es: 'calle', ua: 'street' },
    { es: 'presentar', ua: 'to introduce, present' },
    { es: 'blanco', ua: 'white' }
]

const wordPairs1000 = [
    { es: '¿cómo está usted? ', ua: ' how are you? (formal)' },
    { es: '¿cómo estás? ', ua: ' how are you? (informal)' },
    { es: '¿qué tal? ', ua: ' how are you? (informal) / what’s up?' },
    { es: '¿cómo te va? ', ua: ' how ‘s it going?' },
    { es: '¿qué haces? ', ua: ' what are you doing?' },
    { es: '¿qué pasa? ', ua: ' what ‘s happening?' },
    { es: '¿y tú? ', ua: ' and you?' },
    { es: 'muy bien ', ua: ' very well' },
    { es: 'así, así ', ua: ' so, so' },
    { es: 'mal ', ua: ' bad' },
    { es: 'como siempre ', ua: ' as always' },
    { es: '¡de nada! ', ua: ' you’re welcome! / no problem!' },
    { es: 'por favor ', ua: ' please' },
    { es: '¡perdon! ', ua: ' excuse me!' },
    { es: '¡disculpe! ', ua: ' excuse me!' },
    { es: '¡lo siento! ', ua: ' sorry!' },
    { es: 'gracias ', ua: ' thank you' },
    { es: 'salud ', ua: ' bless you' },
    { es: '¿qué…? ', ua: ' what?' },
    { es: '¿quién…? ', ua: ' who?' },
    { es: '¿cuándo…? ', ua: ' when?' },
    { es: '¿dónde…? ', ua: ' where?' },
    { es: '¿por qué…? ', ua: ' why?' },
    { es: '¿cuál? ', ua: ' which?' },
    { es: '¿cómo…? ', ua: ' how?' },
    { es: 'Yo ', ua: ' I' },
    { es: 'tú (informal) ', ua: ' you' },
    { es: 'usted (formal) ', ua: ' you' },
    { es: 'él ', ua: ' he' },
    { es: 'ella ', ua: ' she' },
    { es: 'nosotros/nosotras ', ua: ' we' },
    { es: 'ustedes ', ua: ' you all' },
    { es: 'ellos ', ua: ' they' },
    { es: 'ellas(females) ', ua: ' they' },
    { es: 'hola ', ua: ' hello' },
    { es: 'buenos días ', ua: ' good morning' },
    { es: 'buenas tardes ', ua: ' good afternoon' },
    { es: 'buenas noches ', ua: ' good evening / good night' },
    { es: '(yo) tengo … años ', ua: ' i am … years old.' },
    { es: 'old ', ua: ' viejo/a' },
    { es: 'young ', ua: ' joven' },
    { es: 'middle-aged ', ua: ' de mediana edad' },
    { es: 'youthful ', ua: ' juvenil' },
    { es: 'nuevo/a', ua: 'new' },
    { es: '¡feliz cumpleaños! ', ua: ' happy birthday!' },
    { es: '¡felicitaciones! ', ua: ' congratulations!' },
    { es: '¡diviértete! ', ua: ' have fun!' },
    { es: '¡buen provecho! ', ua: ' bon appetit!' },
    { es: '¡bienvenidos! / ¡bienvenidas! ', ua: ' welcome!' },
    { es: 'salud! ', ua: ' cheers!' },
    { es: 'adiós ', ua: ' goodbye' },
    { es: 'chao ', ua: ' goodbye' },
    { es: 'hasta luego ', ua: ' see you later (most likely today)' },
    { es: 'hasta mañana ', ua: ' see you tomorrow' },
    { es: 'nos vemos ', ua: ' see you (informal)' },
    { es: '¡cuídate mucho! ', ua: ' take care!' },
    { es: '¡tenga un buen día! ', ua: ' have a nice day!' },
    { es: '¡hasta luego! ', ua: ' see you soon!' },
    { es: '¡buen viaje! ', ua: ' have a good trip!' },
    { es: 'Domingo ', ua: ' Sunday' },
    { es: 'Lunes ', ua: ' Monday' },
    { es: 'Martes ', ua: ' Tuesday' },
    { es: 'Miércoles ', ua: ' Wednesday' },
    { es: 'Jueves ', ua: ' Thursday' },
    { es: 'Viernes ', ua: ' Friday' },
    { es: 'Sabado ', ua: ' Saturday' },
    { es: 'Enero ', ua: ' January' },
    { es: 'Febrero ', ua: ' February' },
    { es: 'Marzo ', ua: ' March' },
    { es: 'Abril ', ua: ' April' },
    { es: 'Mayo ', ua: ' May' },
    { es: 'Junio ', ua: ' June' },
    { es: 'Julio ', ua: ' July' },
    { es: 'Agosto ', ua: ' August' },
    { es: 'Septiembre ', ua: ' September' },
    { es: 'Octubre ', ua: ' October' },
    { es: 'Noviembre ', ua: ' November' },
    { es: 'Diciembre ', ua: ' December' },
    { es: 'anteayer ', ua: ' day before yesterday' },
    { es: 'ayer ', ua: ' yesterday' },
    { es: 'el año ', ua: ' year' },
    { es: 'el día ', ua: ' day' },
    { es: 'el mes ', ua: ' month' },
    { es: 'el siglo ', ua: ' century' },
    { es: 'la hora ', ua: ' hour' },
    { es: 'hoy ', ua: ' today' },
    { es: 'la semana ', ua: ' week' },
    { es: 'madrugada ', ua: ' dawn, very early in the morning' },
    { es: 'mañana ', ua: ' tomorrow' },
    { es: 'mañana ', ua: ' morning' },
    { es: 'medianoche ', ua: ' midnight' },
    { es: 'mediodia ', ua: ' noon' },
    { es: 'el minuto ', ua: ' minute' },
    { es: 'la noche ', ua: ' night' },
    { es: 'el pasado mañana ', ua: ' day after tomorrow' },
    { es: 'los segundos ', ua: ' seconds' },
    { es: 'la tarde ', ua: ' afternoon' },
    { es: 'el padre ', ua: ' father' },
    { es: 'el papá ', ua: '  dad' },
    { es: 'la madre ', ua: ' mother' },
    { es: 'la mamá ', ua: ' mom' },
    { es: 'el hermano ', ua: '  brother' },
    { es: 'la hermana ', ua: ' sister' },
    { es: 'el hijo ', ua: ' son' },
    { es: 'la hija ', ua: ' daughter' },
    { es: 'la familia cercana ', ua: '  close family' },
    { es: 'el abuelo ', ua: ' grandfather' },
    { es: 'la abuela ', ua: ' grandmother' },
    { es: 'el bisabuelo ', ua: ' great-grandfather' },
    { es: 'la bisabuela ', ua: ' great-grandmother' },
    { es: 'la nieta ', ua: ' granddaughter' },
    { es: 'el nieto ', ua: ' grandson' },
    { es: 'el tío ', ua: ' uncle' },
    { es: 'la tía ', ua: ' aunt' },
    { es: 'el tío abuelo ', ua: ' great-uncle' },
    { es: 'la tía abuela ', ua: ' great-aunt' },
    { es: 'el primo ', ua: ' cousin (male)' },
    { es: 'la prima ', ua: ' cousin (female)' },
    { es: 'mis parientes ', ua: ' my relatives' },
    { es: 'abrazar ', ua: ' to hug' },
    { es: 'amar ', ua: ' to love' },
    { es: 'reír ', ua: ' to laugh' },
    { es: 'perdonar ', ua: ' to forgive' },
    { es: 'empezar ', ua: '  to start' },
    { es: 'seguir ', ua: ' to follow' },
    { es: 'abrir ', ua: '  to open' },
    { es: 'buscar ', ua: ' to search' },
    { es: 'cantar ', ua: ' to sing' },
    { es: 'cerrar ', ua: ' to close' },
    { es: 'destruir ', ua: ' to destroy' },
    { es: 'dormir ', ua: ' to sleep' },
    { es: 'encontrar ', ua: ' to find' },
    { es: 'esconder ', ua: ' to hide' },
    { es: 'esperar ', ua: ' to wait' },
    { es: 'faltar ', ua: ' to miss' },
    { es: 'hacer ', ua: ' to do' },
    { es: 'intentar ', ua: ' to try' },
    { es: 'llamar ', ua: ' to call' },
    { es: 'llevar ', ua: ' to take' },
    { es: 'llorar ', ua: ' to cry' },
    { es: 'luchar ', ua: ' to fight' },
    { es: 'mentir ', ua: ' to lie' },
    { es: 'odiar ', ua: ' to hate' },
    { es: 'recibir ', ua: ' to receive' },
    { es: 'reconocer ', ua: ' to recognize' },
    { es: 'robar ', ua: ' to steal' },
    { es: 'salvar ', ua: ' to save' },
    { es: 'sonreír ', ua: ' to smile' },
    { es: 'soñar ', ua: ' to dream' },
    { es: 'tomar ', ua: ' to take' },
    { es: 'Vivir ', ua: ' to live' },
    { es: 'tranquilo/a ', ua: ' quiet' },
    { es: 'ruidoso/a ', ua: ' loud' },
    { es: 'gritar ', ua: ' to shout' },
    { es: 'escuchar ', ua: ' to hear' },
    { es: 'silencio ', ua: ' silence' },
    { es: 'alto ', ua: ' loud' },
    { es: 'bajo ', ua: ' soft' },
    { es: 'ensordecedor ', ua: ' deafening' },
    { es: 'agudo ', ua: ' sharp, high-pitched' },
    { es: 'grave ', ua: ' low-pitched' },
    { es: 'melodioso ', ua: ' melodious' },
    { es: 'armónico ', ua: ' harmonic' },
    { es: 'zumbido ', ua: ' buzz' },
    { es: 'sordo ', ua: ' deaf' },
    { es: 'duro de oíd ', ua: ' hard of hearing' },
    { es: 'oído fino ', ua: ' acute hearing' },
    { es: 'problemas de audición ', ua: ' hearing-impaired' },
    { es: 'fuera de alcance ', ua: ' out of earshot' },
    { es: 'ver ', ua: ' to see' },
    { es: 'mirar ', ua: ' to look' },
    { es: 'de colores', ua: ' colorful' },
    { es: 'blanco y negro ', ua: ' black and white' },
    { es: 'brillante ', ua: ' bright' },
    { es: 'apagado ', ua: ' dim' },
    { es: 'claro ', ua: ' light' },
    { es: 'oscuro ', ua: ' dark' },
    { es: 'ciego ', ua: ' blind' },
    { es: 'mirar fijamente ', ua: ' to stare' },
    { es: 'echar un vistazo ', ua: ' to glance' },
    { es: 'bizquear ', ua: ' to squint' },
    { es: 'guiñar ', ua: ' to wink' },
    { es: 'parpadear ', ua: ' to blink' },
    { es: 'tocar ', ua: ' to touch' },
    { es: 'agarrar ', ua: ' to grab' },
    { es: 'suave ', ua: ' soft' },
    { es: 'áspero(a) ', ua: ' rough' },
    { es: 'liso(a) ', ua: ' smooth' },
    { es: 'rugoso(a) ', ua: ' wrinkled' },
    { es: 'pegajoso(a) ', ua: ' sticky' },
    { es: 'punzante ', ua: ' sharp' },
    { es: 'sedoso(a) ', ua: ' silky' },
    { es: 'esponjoso(a) ', ua: ' spongy' },
    { es: 'mullido(a) ', ua: ' fluffy' },
    { es: 'hormigueo ', ua: ' tingle' },
    { es: 'entumecido(a) ', ua: ' numb' },
    { es: 'rozar ', ua: ' to touch gently' },
    { es: 'acariciar ', ua: ' to caress' },
    { es: 'agarrar ', ua: ' to grab' },
    { es: 'olor ', ua: ' smell' },
    { es: 'el perfume ', ua: ' scent' },
    { es: 'la fragancia ', ua: ' fragrance' },
    { es: 'el hedor ', ua: ' stench' },
    { es: 'apestoso(a) ', ua: ' smelly' },
    { es: 'fresco(a)  ', ua: ' fresh' },
    { es: 'acre ', ua: ' pungent' },
    { es: 'húmedo(a) ', ua: ' musty' },
    { es: 'podrido(a) ', ua: ' rotten' },
    { es: 'ahumado(a) ', ua: ' smoky' },
    { es: 'apestar ', ua: ' to stink' },
    { es: 'gusto ', ua: '- taste' },
    { es: 'sabor ', ua: ' flavor' },
    { es: 'probar ', ua: ' try' },
    { es: 'sabroso ', ua: ' está sabrosa' },
    { es: 'delicioso ', ua: ' delicious' },
    { es: 'perfecto ', ua: ' perfect' },
    { es: 'apetitoso ', ua: ' appetizing' },
    { es: 'dulce ', ua: ' sweet' },
    { es: 'dulzón ', ua: ' sugary' },
    { es: 'soso ', ua: ' bland' },
    { es: 'abierto/a ', ua: ' open' },
    { es: 'ancho/a ', ua: ' wide' },
    { es: 'estrecho/a ', ua: ' narrow' },
    { es: 'lejano/a ', ua: ' far' },
    { es: 'cercano/a ', ua: ' close' },
    { es: 'alegre ', ua: ' joyful' },
    { es: 'gracioso/a ', ua: ' funny, amusing' },
    { es: 'serio/a ', ua: ' serious' },
    { es: 'tímido/a ', ua: ' shy' },
    { es: 'valiente ', ua: ' brave' },
    { es: 'loco/a', ua: 'crazy' },
    { es: 'contento(a) ', ua: ' content' },
    { es: 'feliz ', ua: ' happy' },
    { es: 'preocupado(a) ', ua: ' worried' },
    { es: 'nervioso(a) ', ua: ' nervous' },
    { es: 'tranquilo(a) ', ua: ' tranquil' },
    { es: 'calmado(a) ', ua: ' calm' },
    { es: 'emocionado(a) ', ua: ' excited' },
    { es: 'excitado(a) ', ua: ' excited' },
    { es: 'largo/a ', ua: ' long' },
    { es: 'corto/a ', ua: ' short' },
    { es: 'liso/a ', ua: ' straight' },
    { es: 'rizado/a ', ua: ' curly' },
    { es: 'ondulado/a ', ua: ' wavy' },
    { es: 'castaño/a ', ua: ' brown' },
    { es: 'rubio/a ', ua: ' blonde' },
    { es: 'pelirrojo/a ', ua: ' red' },
    { es: 'negro/a ', ua: ' black' },
    { es: 'canoso/a ', ua: ' grey' },
    { es: 'abundante ', ua: ' thick' },
    { es: 'fino/a ', ua: ' thin' },
    { es: 'escalado/a ', ua: ' layered' },
    { es: 'teñido/a ', ua: ' dyed' },
    { es: 'saludable ', ua: ' healthy' },
    { es: 'claro/a ', ua: ' light' },
    { es: 'encrespado/a ', ua: ' frizzy' },
    { es: 'brillante ', ua: ' shiny' },
    { es: 'calvo/a ', ua: ' bald' },
    { es: 'grande', ua: 'big' },
    { es: 'pequeño/a', ua: 'small' },
    { es: 'enorme', ua: 'huge' },
    { es: 'delgado/a ', ua: ' lean' },
    { es: 'esbelto/a ', ua: ' slender' },
    { es: 'flaco/a ', ua: ' skinny' },
    { es: 'menudo/a ', ua: ' petite' },
    { es: 'alto/a ', ua: ' tall' },
    { es: 'bajo/a ', ua: ' short' },
    { es: 'hermoso/a ', ua: ' beautiful' },
    { es: 'guapo/a ', ua: ' handsome' },
    { es: 'feo/a ', ua: ' ugly' },
    { es: 'adorable ', ua: ' cute' },
    { es: 'bonita ', ua: ' pretty' },
    { es: 'impresionante ', ua: ' stunning' },
    { es: 'poco atractivo/a ', ua: ' plain' },
    { es: 'promedio/a ', ua: ' average' },
    { es: 'atractivo/a ', ua: ' attractive' },
    { es: 'negro ', ua: '  black' },
    { es: 'marrón / café ', ua: ' brown' },
    { es: 'gris ', ua: ' grey' },
    { es: 'blanco ', ua: ' white' },
    { es: 'amarillo ', ua: '  yellow' },
    { es: 'anaranjado ', ua: ' orange' },
    { es: 'rojo ', ua: ' red' },
    { es: 'rosado ', ua: '  pink' },
    { es: 'morado / púrpura ', ua: ' purple' },
    { es: 'azul ', ua: '  blue' },
    { es: 'verde ', ua: ' green' },
    { es: 'colorear ', ua: ' to color' },
    { es: 'construir ', ua: ' to construct' },
    { es: 'cortar ', ua: ' to cut' },
    { es: 'coser ', ua: ' to sew' },
    { es: 'dibujar ', ua: ' to draw' },
    { es: 'pintar ', ua: ' to paint' },
    { es: 'cero ', ua: ' zero' },
    { es: 'uno ', ua: ' one' },
    { es: 'dos ', ua: ' two' },
    { es: 'tres ', ua: ' three' },
    { es: 'cuatro ', ua: ' four' },
    { es: 'cinco ', ua: '  five' },
    { es: 'seis ', ua: ' six' },
    { es: 'siete ', ua: ' seven' },
    { es: 'ocho ', ua: '  eight' },
    { es: 'nueve ', ua: ' nine' },
    { es: 'diez ', ua: ' ten' },
    { es: 'el gato ', ua: ' cat' },
    { es: 'el perro ', ua: ' dog' },
    { es: 'el conejo ', ua: ' rabbit' },
    { es: 'el pollo ', ua: ' chicken' },
    { es: 'la gallina ', ua: ' hen' },
    { es: 'el gallo ', ua: '  rooster' },
    { es: 'la vaca ', ua: '  cow' },
    { es: 'el toro ', ua: '  bull' },
    { es: 'la oveja ', ua: '  sheep' },
    { es: 'el caballo ', ua: ' horse' },
    { es: 'el cerdo ', ua: ' pig' },
    { es: 'la cabra ', ua: '  goat' },
    { es: 'el burro ', ua: '  donkey' },
    { es: 'el ratón ', ua: '  mouse' },
    { es: 'el ciervo ', ua: '  deer' },
    { es: 'el mapache ', ua: '  raccoon' },
    { es: 'la ardilla -', ua: ' squirrel' },
    { es: 'el búho ', ua: '  owl' },
    { es: 'el zorro ', ua: '  fox' },
    { es: 'el lobo ', ua: '  wolf' },
    { es: 'el oso ', ua: '  bear' },
    { es: 'el cangrejo ', ua: ' crab' },
    { es: 'la medusa ', ua: ' jellyfish' },
    { es: 'el delfín ', ua: '  dolphin' },
    { es: 'la ballena ', ua: '  whale' },
    { es: 'el tiburón ', ua: '  shark' },
    { es: 'la foca ', ua: '  seal' },
    { es: 'el lobo marino ', ua: '  sea lion' },
    { es: 'la morsa ', ua: '  walrus' },
    { es: 'el pingüino ', ua: ' penguin' },
    { es: 'el viaje ', ua: ' trip' },
    { es: 'el equipaje ', ua: ' bags' },
    { es: 'la salida ', ua: ' exit' },
    { es: 'la llegada ', ua: ' arrival' },
    { es: 'los documentos de identidad ', ua: ' id papers' },
    { es: 'el billete de avión ', ua: ' boarding pass' },
    { es: 'el hotel ', ua: ' hotel' },
    { es: 'el permiso de conducir ', ua: ' driver’s license' },
    { es: 'echar gasolina ', ua: ' to get gas' },
    { es: 'viajar ', ua: ' to travel' },
    { es: 'volver ', ua: ' to return' },
    { es: 'ir ', ua: ' to go' },
    { es: 'salir ', ua: ' to leave' },
    { es: 'parar ', ua: ' to stop' },
    { es: 'partir ', ua: ' to depart' },
    { es: 'porter(a) ', ua: ' doorman' },
    { es: 'hostia ', ua: ' hostess' },
    { es: 'botones ', ua: ' bellhop' },
    { es: 'anfitriona', ua: ' airline hostess' },
    { es: 'el avión ', ua: '  airplane' },
    { es: 'el coche ', ua: '  car' },
    { es: 'la bicicleta ', ua: ' bicycle' },
    { es: 'la motocicleta ', ua: ' motorcycle' },
    { es: 'el tren ', ua: '  train' },
    { es: 'el metro/subte ', ua: '  subway' },
    { es: 'el autobús ', ua: ' bus' },
    { es: 'el barco ', ua: ' ship' },
    { es: 'taxista ', ua: ' taxi driver' },
    { es: 'revisor(a) ', ua: ' train conductor' },
    { es: 'dependiente de gas ', ua: ' gas station attendant' },
    { es: 'conductor(a) ', ua: ' driver, chauffeur' },
    { es: 'camionero(a) ', ua: ' truck driver' },
    { es: 'el sol ', ua: '  the sun' },
    { es: 'las nubes ', ua: '  the clouds' },
    { es: 'la niebla ', ua: ' the fog' },
    { es: 'la neblina ', ua: ' the mist' },
    { es: 'la lluvia ', ua: '  the rain' },
    { es: 'la llovizna ', ua: ' the drizzle' },
    { es: 'la tormenta ', ua: '  the storm' },
    { es: 'el tornado ', ua: '  the tornado' },
    { es: 'el trueno ', ua: ' the thunder' },
    { es: 'el relámpago ', ua: ' the lightning strike' },
    { es: 'el rayo ', ua: ' the lightning bolt' },
    { es: 'el viento ', ua: ' the wind' },
    { es: 'la brisa ', ua: ' the breeze' },
    { es: 'el granizo ', ua: ' the hail' },
    { es: 'el hielo ', ua: ' the ice' },
    { es: 'la nieve ', ua: '  the snow' },
    { es: 'el calor ', ua: '  the heat' },
    { es: 'el frío ', ua: '  the cold' },
    { es: 'la humedad ', ua: ' the humidity' },
    { es: 'la temperatura ', ua: ' the temperature' },
    { es: 'el pronóstico ', ua: ' the forecast' },
    { es: 'llover ', ua: '  to rain' },
    { es: 'lloviznar ', ua: '  to drizzle' },
    { es: 'diluviar ', ua: ' to pour down' },
    { es: 'granizar ', ua: ' to hail' },
    { es: 'nevar ', ua: '  to snow' },
    { es: 'el invierno ', ua: '  winter' },
    { es: 'la primavera ', ua: '  spring' },
    { es: 'el verano ', ua: '  summer' },
    { es: 'el otoño ', ua: '  fall' },
    { es: 'carta de motivación ', ua: ' cover letter' },
    { es: 'el cv ', ua: ' resume' },
    { es: 'la firma ', ua: ' firm' },
    { es: 'el negocio ', ua: ' business' },
    { es: 'la compañía ', ua: ' company' },
    { es: 'el jefe ', ua: ' boss' },
    { es: 'el empleado ', ua: ' employee' },
  { es: 'trabajar ', ua: ' to work' },
  { es: 'negociar ', ua: ' to negotiate' },
  { es: 'consultor(a) ', ua: '  consultant' },
  { es: 'dueño(a) ', ua: ' owner' },
  { es: 'abogado(a) ', ua: ' lawyer' },
  { es: 'arquitecto(a) ', ua: ' architect' },
  { es: 'bombero(a) ', ua: ' fireman' },
  { es: 'campesino(a) ', ua: ' farm worker' },
  { es: 'carpintero(a) ', ua: ' carpenter' },
  { es: 'cartero(a) ', ua: ' postal worker' },
  { es: 'casero(a) ', ua: ' landlord' },
  { es: 'científico(a) ', ua: ' scientist' },
  { es: 'cocinero(a) ', ua: ' cook, chef' },
  { es: 'consejero (a) ', ua: ' counselor' },
  { es: 'constructor (a) ', ua: ' construction worker' },
  { es: 'contador(a) ', ua: ' accountant/bookkeeper' },
  { es: 'doméstico(a) ', ua: '  maid' },
  { es: 'detective ', ua: ' detective' },
  { es: 'director, revisor, redactor(a) ', ua: ' editor' },
  { es: 'electricista ', ua: ' electrician' },
  { es: 'escritor / autor(a) ', ua: ' writer / author' },
  { es: 'vaquero, tropero(a) ', ua: ' cowboy' },
  { es: 'manejador(a) ', ua: ' manager' },
  { es: 'granjero(a) ', ua: ' farmer' },
  { es: 'ingeniero(a) ', ua: ' engineer' },
  { es: 'jardinero(a) ', ua: ' gardener' },
  { es: 'jefe ', ua: ' boss' },
  { es: 'juez ', ua: ' judge' },
  { es: 'lavandero(a) ', ua: ' laundry person' },
  { es: 'marinero(a) ', ua: '  merchant marine' },
  { es: 'mecánico (a) ', ua: ' mechanic' },
  { es: 'camarero(a) ', ua: ' waiter' },
  { es: 'padre ', ua: ' priest' },
  { es: 'panadero(a) ', ua: ' baker' },
  { es: 'pastor(a) ', ua: ' pastor/minister' },
  { es: 'periodista ', ua: ' reporter/journalist' },
  { es: 'pescador(a) ', ua: ' fisherman' },
  { es: 'pintor(a) ', ua: ' painter' },
  { es: 'plomero(a) ', ua: ' plumber' },
  { es: 'Policía ', ua: ' policeman' },
  { es: 'programador(a) ', ua: ' computer programmer' },
  { es: 'dueño(a) ', ua: ' owner' },
  { es: 'químico(a) ', ua: ' chemist' },
  { es: 'ranchero(a) ', ua: ' rancher' },
  { es: 'rebuscador(a) ', ua: ' researcher' },
  { es: 'reparador(a) ', ua: ' repairman' },
  { es: 'técnico(a) de laboratorio ', ua: ' lab technician' },
  { es: 'trabajador(a) de fábrica ', ua: ' factory worker' },
  { es: 'veterinario(a) ', ua: ' veterinarian' },
  { es: 'ir al gimnasio ', ua: ' go to the gym' },
  { es: 'ir de caminata ', ua: ' go hiking' },
  { es: 'levantar pesas ', ua: ' lift weight' },
  { es: 'mantenerse en forma ', ua: ' to stay in shape' },
  { es: 'practicar ', ua: ' to practice' },
  { es: 'nadar ', ua: ' to swim' },
  { es: 'el yoga ', ua: ' yoga' },
  { es: 'el fútbol ', ua: ' soccer' },
  { es: 'el fútbol americano ', ua: ' football' },
  { es: 'el béisbol ', ua: ' baseball' },
  { es: 'el baloncesto ', ua: ' basketball' },
  { es: 'el golf ', ua: ' golf' },
  { es: 'el hockey ', ua: ' hockey' },
  { es: 'el tenis ', ua: ' tennis' },
  { es: 'el voleibol ', ua: ' volleyball' },
  { es: 'luchar ', ua: ' to wrestle/to fight' },
  { es: 'correr ', ua: ' to run' },
  { es: 'esquiar ', ua: ' to ski' },
  { es: 'el partido ', ua: ' game/match' },
  { es: 'la carrera ', ua: ' race' },
  { es: 'el torneo ', ua: ' tournament' },
  { es: 'patear ', ua: ' to kick' },
  { es: 'saltar ', ua: ' to jump' },
  { es: 'parar ', ua: ' to stop/to block' },
  { es: 'balancear ', ua: ' to swing' },
  { es: 'servir ', ua: ' to serve' },
  { es: 'rematar ', ua: ' to spike' },
  { es: 'pegar ', ua: ' to hit' },
  { es: 'driblar ', ua: ' to dribble' },
  { es: 'tirar ', ua: ' to throw' },
  { es: 'agarrar ', ua: ' to catch' },
  { es: 'ganar ', ua: ' to win' },
  { es: 'perder ', ua: ' to lose' },
  { es: 'empatar ', ua: ' to tie' },
  { es: 'caminar ', ua: ' to walk' },
  { es: 'bailar ', ua: ' to dance' },
  { es: 'jugar ', ua: ' to play' },
  { es: 'competir ', ua: ' to compete' },
  { es: 'la comida ', ua: ' food' },
  { es: 'las bebidas ', ua: ' drinks' },
  { es: 'las verduras ', ua: ' vegetables' },
  { es: 'las frutas ', ua: ' fruits' },
  { es: 'cocinar ', ua: ' to cook' },
  { es: 'tengo hambre ', ua: ' i’m hungry' },
  { es: 'tengo sed ', ua: ' i’m thirsty' },
  { es: 'la res ', ua: '  beef' },
  { es: 'el pollo ', ua: ' chicken' },
  { es: 'la gallina ', ua: ' chicken' },
  { es: 'el cordero ', ua: '  lamb' },
  { es: 'la barbacoa ', ua: '  grilled' },
  { es: 'el cerdo ', ua: ' pork' },
  { es: 'el perrito caliente ', ua: ' hot dog' },
  { es: 'el jamón ', ua: ' ham' },
  { es: 'la hamburguesa ', ua: ' hamburger' },
  { es: 'el tocino ', ua: '  bacon' },
  { es: 'el pescado ', ua: ' fish' },
  { es: 'la zanahoria ', ua: '  carrot' },
  { es: 'la lechuga ', ua: '  lettuce' },
  { es: 'el tomate ', ua: ' tomato' },
  { es: 'la maíz ', ua: ' corn' },
  { es: 'la papa ', ua: ' potato' },
  { es: 'la patata  ', ua: ' potato' },
  { es: 'las papas ', ua: '  french fries' },
  { es: 'las patatas fritas ', ua: '  french fries' },
  { es: 'el brocoli ', ua: '  broccoli' },
  { es: 'la espinaca ', ua: '  spinach' },
  { es: 'la cebolla ', ua: '  onion' },
  { es: 'la col ', ua: '  cabbage' },
  { es: 'la ensalada ', ua: ' salad' },
  { es: 'la aceituna ', ua: '  olive' },
  { es: 'las calabacitas ', ua: '  squash' },
  { es: 'el hongo ', ua: '  mushroom' },
  { es: 'el pepino ', ua: '  cucumber' },
  { es: 'la manzana ', ua: '  apple' },
  { es: 'la pera ', ua: '  pear' },
  { es: 'la fresa ', ua: '  strawberry' },
  { es: 'la frambuesa ', ua: '  raspberry' },
  { es: 'la zarzamora ', ua: ' blackberry' },
  { es: 'el arándano ', ua: '  blueberry' },
  { es: 'el arándano rojo ', ua: ' cranberry' },
  { es: 'la naranja ', ua: '  orange' },
  { es: 'la mandarina ', ua: '  tangerine' },
  { es: 'la toronja ', ua: '  grapefruit' },
  { es: 'el limón ', ua: '  lemon' },
  { es: 'la lima ', ua: '  lime' },
  { es: 'el plátano ', ua: '  banana' },
  { es: 'la piña ', ua: '  pineapple' },
  { es: 'el coco ', ua: '  coconut' },
  { es: 'el mango ', ua: '  mango' },
  { es: 'la papaya ', ua: ' papaya' },
  { es: 'la cerveza ', ua: ' beer' },
  { es: 'el refresco ', ua: ' pop, soft drink' },
  { es: 'el té ', ua: '  tea' },
  { es: 'el té helado ', ua: '  iced tea' },
  { es: 'el café ', ua: '  coffee' },
  { es: 'la leche ', ua: '  milk' },
  { es: 'el agua ', ua: '  water' },
  { es: 'el jugo ', ua: ' juice' },
  { es: 'el batido ', ua: ' milkshake' },
  { es: 'el chocolate ', ua: '  chocolate' },
  { es: 'los dulces ', ua: '  candy' },
  { es: 'el pastel ', ua: '  cake' },
  { es: 'las galletas ', ua: '  cookies' },
  { es: 'el helado ', ua: '  ice cream' },
  { es: 'el churros con chocolate ', ua: '  chocolate churros' },
  { es: 'el basque cheesecake ', ua: '  cheesecake' },
  { es: 'el plato ', ua: '  plate' },
  { es: 'el plato hondo ', ua: '  bowl' },
  { es: 'el vaso ', ua: '  glass' },
  { es: 'la copa ', ua: ' cup' },
  { es: 'el tenedor ', ua: '  fork' },
  { es: 'la cuchara ', ua: '  spoon' },
  { es: 'el cuchillo ', ua: '  knife' },
  { es: 'la servilleta ', ua: '  napkin' },
  { es: 'dulce ', ua: ' sweet' },
  { es: 'salado(a) ', ua: ' savory' },
  { es: 'rico(a) ', ua: ' delicious' },
  { es: 'el desayuno ', ua: ' breakfast' },
  { es: 'el almuerzo ', ua: ' lunch' },
  { es: 'la cena ', ua: ' dinner' },
  { es: 'el tentempié ', ua: ' snack' },
  { es: 'la prenda, la ropa ', ua: ' clothes' },
  { es: 'los zapatos ', ua: ' shoes' },
  { es: 'el pantalón ', ua: ' pants' },
  { es: 'la camiseta / la camisa ', ua: ' shirt' },
  { es: 'la chaqueta ', ua: ' jacket' },
  { es: 'la falda ', ua: ' skirt' },
  { es: 'el suéter ', ua: ' sweater' },
  { es: 'el vestido ', ua: ' dress' },
  { es: 'la navidad ', ua: ' christmas' },
  { es: 'el año nuevo', ua: ' new year' },
  { es: 'la pascua ', ua: '  easter' },
  { es: 'el día de san valentín ', ua: ' valentine’s day' },
  { es: 'el día de la madre ', ua: ' mother’s day' },
  { es: 'el día del padre ', ua: ' father’s day' },
  { es: 'el día de la independencia ', ua: ' independence day' },
  { es: 'el día de acción de gracias ', ua: ' thanksgiving' },
  { es: 'el cumpleaños ', ua: ' birthday' },
  { es: 'la fiesta ', ua: ' the party' },
  { es: 'la boda ', ua: ' the wedding' },
  { es: 'el cuerpo humano ', ua: ' the human body' },
  { es: 'la cabeza ', ua: ' head' },
  { es: 'el pecho ', ua: ' chest' },
  { es: 'el oído / la oreja ', ua: ' ear' },
  { es: 'el ojo ', ua: ' eye' },
  { es: 'la cara ', ua: ' face' },
  { es: 'la mano ', ua: ' hand' },
  { es: 'la boca ', ua: ' mouth' },
  { es: 'el pie ', ua: ' foot' },
  { es: 'la espalda ', ua: ' back' },
  { es: 'el pelo  ', ua: ' hair' },
  { es: 'el codo ', ua: ' elbow' },
  { es: 'el dedo ', ua: ' finger' },
  { es: 'la pantorrilla ', ua: ' calf' },
  { es: 'la pierna ', ua: ' leg' },
  { es: 'la muñeca ', ua: ' wrist' },
  { es: 'el talón ', ua: ' heel' },
  { es: 'el brazo ', ua: ' arm' },
  { es: 'el cuello ', ua: ' neck' },
  { es: 'el tobillo ', ua: ' ankle' },
  { es: 'la frente ', ua: ' forehead' },
  { es: 'el muslo ', ua: ' thigh' },
  { es: 'la barba ', ua: ' beard' },
  { es: 'el bigote ', ua: ' mustache' },
  { es: 'la lengua ', ua: ' tongue' },
  { es: 'el dedo del pie ', ua: ' toe' },
  { es: 'la cintura ', ua: ' waist' },
  { es: 'la cadera ', ua: ' hip' },
  { es: 'las nalgas ', ua: ' buttocks' },
  { es: 'el pulgar ', ua: ' thumb' },
  { es: 'la rodilla ', ua: ' knee' },
  { es: 'la nariz ', ua: ' nose' },
  { es: 'la mejilla, el cachete ', ua: ' cheek' },
  { es: 'los labios ', ua: ' lips' },
  { es: 'el hombro ', ua: ' shoulder' },
  { es: 'la barbilla, el mentón ', ua: ' chin' },
  { es: 'las cejas ', ua: ' eyebrows' },
  { es: 'las pestañas ', ua: ' eyelashes' },
  { es: 'el ombligo  ', ua: ' belly button' },
  { es: 'la piel  ', ua: ' skin' },
  { es: 'el vientre ', ua: ' stomach' },
  { es: 'la garganta ', ua: ' throat' },
  { es: 'los dientes/las muelas ', ua: ' teeth' },
  { es: 'al principio ', ua: ' at the beginning' },
  { es: 'en primer lugar ', ua: ' firstly' },
  { es: 'para comenzar ', ua: ' to start' },
  { es: 'antes ', ua: ' before' },
  { es: 'después ', ua: ' after' },
  { es: 'a continuación  ', ua: ' in continuation' },
  { es: 'mientras tanto ', ua: ' meanwhile' },
  { es: 'al final ', ua: ' at the end' },
  { es: 'además ', ua: ' additionally' },
  { es: 'aparte de ', ua: ' apart from' },
  { es: 'asimismo ', ua: ' at the same time' },
  { es: 'también ', ua: ' also' },
  { es: 'de igual manera  ', ua: ' in the same way' },
  { es: 'pero  ', ua: ' but' },
  { es: 'sin embargo  ', ua: ' however' },
  { es: 'no obstante  ', ua: ' nevertheless' },
  { es: 'por otro lado  ', ua: ' on the other hand' },
  { es: 'aunque  ', ua: ' even though' },
  { es: 'a pesar de  ', ua: ' despite' },
  { es: 'dentro de ', ua: ' inside of' },
  { es: 'encima de/sobre ', ua: ' on top of' },
  { es: 'debajo de ', ua: ' underneath of' },
  { es: 'delante de ', ua: ' in front of' },
  { es: 'detrás de ', ua: ' behind' },
  { es: 'entre ', ua: ' between' },
  { es: 'en ', ua: ' in/on/at' },
  { es: 'dentro de ', ua: ' inside of' },
  { es: 'fuera de ', ua: ' outside of' },
  { es: 'arriba de ', ua: ' above' },
  { es: 'en medio de ', ua: ' in the middle of' },
  { es: 'cerca de ', ua: ' close to' },
  { es: 'lejos de ', ua: ' far from' },
  { es: 'al lado de ', ua: ' next to' },
  { es: 'alrededor de ', ua: ' around' },
  { es: 'a la izquierda de ', ua: ' to the left of' },
  { es: 'a la derecha de ', ua: ' to the right of' },
  { es: 'estar ', ua: ' to be' },
  { es: 'colocar ', ua: ' to place' },
  { es: 'ubicar ', ua: ' to position' },
  { es: 'poner ', ua: ' to put' },
  { es: 'situar ', ua: ' to place' },
  { es: 'aquí, acá ', ua: ' here' },
  { es: 'ahí ', ua: ' there' },
  { es: 'allí ', ua: ' there' },
  { es: 'allá ', ua: ' over there' },
  { es: 'el este ', ua: ' east' },
  { es: 'el norte ', ua: ' north' },
  { es: 'el oeste ', ua: ' west' },
  { es: 'el sur ', ua: ' south' },
  { es: 'la clase ', ua: ' classroom' },
  { es: 'el aula ', ua: ' classroom' },
  { es: 'la pizarra ', ua: ' blackboard' },
  { es: 'el pizarrón ', ua: ' whiteboard' },
  { es: 'la tiza ', ua: ' chalk' },
  { es: 'el marcador ', ua: ' marker' },
  { es: 'el borrador ', ua: ' eraser' },
  { es: 'el escritorio ', ua: ' desk' },
  { es: 'el pupitre ', ua: ' desk' },
  { es: 'la silla ', ua: ' chair' },
  { es: 'la mochila ', ua: ' backpack' },
  { es: 'el libro ', ua: ' book' },
  { es: 'el cuaderno ', ua: ' notebook' },
  { es: 'el papel ', ua: ' paper' },
  { es: 'el lápiz ', ua: ' pencil' },
  { es: 'los lápices de colores ', ua: ' coloring pencils' },
  { es: 'el sacapuntas ', ua: ' pencil sharpener' },
  { es: 'el bolígrafo ', ua: ' pen' },
  { es: 'la goma ', ua: ' eraser' },
  { es: 'las tijeras ', ua: ' scissors' },
  { es: 'la cola/el pegamento ', ua: ' glue' },
  { es: 'la regla ', ua: ' ruler' },
  { es: 'la grapadora ', ua: ' stapler' },
  { es: 'el estuche ', ua: ' pencil case' },
  { es: 'estudiar ', ua: ' to study' },
  { es: 'repasar ', ua: ' to revise' },
  { es: 'aprender ', ua: ' to learn' },
  { es: 'saber ', ua: ' to know' },
  { es: 'hacer los deberes ', ua: ' to do homework' },
  { es: 'hacer la tarea ', ua: ' to do homework' },
  { es: 'leer ', ua: ' to read' },
  { es: 'escribir ', ua: ' to write' },
  { es: 'hablar ', ua: ' to speak' },
  { es: 'decir ', ua: ' to say' },
  { es: 'preguntar ', ua: ' to ask' },
  { es: 'charlar ', ua: ' to chat' },
  { es: 'dictar ', ua: ' to dictate' },
  { es: 'deletrear ', ua: ' to spell' },
  { es: 'contar ', ua: ' to count' },
  { es: 'faltar ', ua: ' to miss school' },
  { es: 'aprobar ', ua: ' to pass a subject/a test' },
  { es: 'reprobar', ua: ' to fail a subject/a test' },
  { es: 'prestar ', ua: ' to lend' },
  { es: 'tomar prestado ', ua: ' to borrow' },
  { es: 'traer ', ua: ' to bring' },
  { es: 'enseñar ', ua: ' to teach' },
  { es: 'mostrar ', ua: ' to show' },
  { es: 'nombrar ', ua: ' to name' },
  { es: 'ayudar ', ua: ' to help' },
  { es: 'la escuela ', ua: ' school' },
  { es: 'el colegio ', ua: ' school' },
  { es: 'el gimnasio ', ua: ' gym' },
  { es: 'el patio ', ua: ' playground' },
  { es: 'el baño ', ua: ' restroom' },
  { es: 'el pasillo ', ua: ' hallway' },
  { es: 'la biblioteca ', ua: ' library' },
  { es: 'la oficina ', ua: ' office' },
  { es: 'la sala de profesores ', ua: ' staff room' },
  { es: 'el comedor ', ua: ' cafeteria' },
  { es: 'la cocina ', ua: ' kitchen' },
  { es: 'la enfermería ', ua: ' infirmary' },
  { es: 'el laboratorio ', ua: ' lab' },
  { es: 'maestro/a ', ua: ' teacher (primary school)' },
  { es: 'profesor/a ', ua: ' teacher (secondary school)' },
  { es: 'entrenador/a ', ua: ' coach' },
  { es: 'enfermero/a ', ua: ' nurse' },
  { es: 'director/a ', ua: ' principal' },
  { es: 'alumno/a ', ua: ' student' },
  { es: 'estudiante ', ua: ' student' },
  { es: 'el almuerzo ', ua: ' lunch' },
  { es: 'el recreo ', ua: ' recess' },
  { es: 'las vacaciones ', ua: ' vacations' },
  { es: 'la comida ', ua: ' food' },
  { es: 'el casillero ', ua: ' locker' },
  { es: 'la materia ', ua: ' subject' },
  { es: 'la matemática ', ua: ' math' },
  { es: 'la biología ', ua: ' biology' },
  { es: 'la química ', ua: ' chemistry' },
  { es: 'la física ', ua: ' physics' },
  { es: 'la educación física ', ua: ' physical education' },
  { es: 'la historia ', ua: ' history' },
  { es: 'la literatura ', ua: ' literature' },
  { es: 'la prueba ', ua: ' test' },
  { es: 'el examen ', ua: ' exam' },
  { es: 'la nota ', ua: ' grade' },
  { es: 'la calificación ', ua: ' grade' },
  { es: 'un ordenador (Spain) ', ua: ' a computer' },
  { es: 'una computadora (Latin America) ', ua: '  a computer' },
  { es: 'una tableta  ', ua: '  a tablet' },
  { es: 'una impresora  ', ua: '  a printer' },
  { es: 'el ratón  ', ua: '  the mouse' },
  { es: 'apagar ', ua: '  to turn on' },
  { es: 'encender  ', ua: '  to turn off' },
  { es: 'el disco duro   ', ua: '  the hard drive' },
  { es: 'el teclado   ', ua: '  the keyboard' },
  { es: 'la tecla  ', ua: '  the key' },
  { es: 'los auriculares   ', ua: '  headphones' },
  { es: 'el micrófono ', ua: '  the mic' },
  { es: 'la pantalla  ', ua: '  the screen' },
  { es: 'la cámara  ', ua: '  the camera' },
  { es: 'los altavoces ', ua: '  the speakers' },
  { es: 'una aplicación ', ua: '  an app' },
  { es: 'base de datos  ', ua: '  database' },
  { es: 'las redes sociales  ', ua: '  social networks' },
  { es: 'el enlace ', ua: '  the link' },
  { es: 'subir ', ua: '  to upload' },
  { es: 'guardar ', ua: '  to save' },
  { es: 'borrar ', ua: '  to delete' },
  { es: 'hacer click ', ua: '  to click' },
  { es: 'bajar/descargar   ', ua: '  to download' },
  { es: 'buscar en Google   ', ua: '  search on Google' },
  { es: 'pirata informático ', ua: '  hacker' },
  { es: 'contraseña ', ua: '  password' },
  { es: 'la casa ', ua: ' house, home' },
  { es: 'el hogar ', ua: ' home' },
  { es: 'la habitación ', ua: ' bedroom' },
  { es: 'el cuarto ', ua: ' bedroom' },
  { es: 'el dormitorio ', ua: ' bedroom' },
  { es: 'la sala ', ua: ' living room' },
  { es: 'el comedor ', ua: ' dining room' },
  { es: 'la cocina ', ua: ' kitchen' },
  { es: 'el baño ', ua: ' bathroom' },
  { es: 'el pasillo ', ua: ' hallway' },
  { es: 'el jardín ', ua: ' yard, garden' },
  { es: 'el garaje ', ua: ' garage' },
  { es: 'cómodo/a ', ua: ' comfortable' },
  { es: 'acogedor ', ua: ' cozy' },
  { es: 'desordenado/a ', ua: ' messy' },
  { es: 'limpio/a ', ua: ' clean' },
  { es: 'la pasta de dientes ', ua: ' toothpaste' },
  { es: 'el cepillo de dientes ', ua: ' toothbrush' },
  { es: 'el jabón ', ua: ' soap' },
  { es: 'el secador de pelo ', ua: ' hair dryer' },
  { es: 'el champú ', ua: ' shampoo' },
  { es: 'el cepillo ', ua: ' brush' },
  { es: 'el papel higiénico ', ua: ' toilet paper' },
  { es: 'la toalla ', ua: ' towel' },
  { es: 'el agua jabonosa ', ua: ' soapy water' },
  { es: 'la bolsa de basura ', ua: ' trash bag' },
  { es: 'el cubo de basura ', ua: ' trash can' },
  { es: 'el cesto de la ropa sucia ', ua: ' laundry basket' },
  { es: 'la navaja de afeitar ', ua: ' razor' },
  { es: 'la maquinilla de afeitar eléctrica ', ua: ' electric razor' },
  { es: 'la crema de afeitar ', ua: ' shaving cream' },
  { es: 'el enjuague bucal ', ua: ' mouthwash' },
  { es: 'el cepillo de pelo ', ua: ' hair brush' },
  { es: 'el peine ', ua: ' comb' },
  { es: 'el limpiador facial ', ua: ' facial cleanser' },
  { es: 'la balanza', ua: ' scale' },
  { es: 'el pañuelo de papel ', ua: ' tissue' },
  { es: 'los juguetes de baño ', ua: ' bath toys' },
  { es: 'la alfombra de baño ', ua: ' bath mat' },
  { es: 'la ducha ', ua: ' shower' },
  { es: 'la bañera ', ua: ' bathtub' },
  { es: 'el fregadero ', ua: ' sink' },
  { es: 'el inodoro ', ua: ' toilet' },
  { es: 'el grifo ', ua: ' faucet' },
  { es: 'el espejo ', ua: ' mirror' },
  { es: 'peinar ', ua: ' to comb' },
  { es: 'cocinar ', ua: '  to cook' },
  { es: 'comer ', ua: ' to eat' },
  { es: 'adobar ', ua: '  to marinate' },
  { es: 'sazonar ', ua: '  to season' },
  { es: 'lavar ', ua: ' to wash' },
  { es: 'cortar ', ua: '  to cut' },
  { es: 'pelar ', ua: '  to peel' },
  { es: 'picar ', ua: '  to chop' },
  { es: 'moler ', ua: '  to grind' },
  { es: 'incorporar ', ua: ' to add' },
  { es: 'mezclar ', ua: ' to mix' },
  { es: 'catir ', ua: ' to whisk' },
  { es: 'licuar ', ua: '  to blend' },
  { es: 'combinar ', ua: '  to combine' },
  { es: 'freír ', ua: ' to fry' },
  { es: 'hervir ', ua: '  to boil' },
  { es: 'colar ', ua: ' to strain' },
  { es: 'cocer ', ua: ' to cook' },
  { es: 'hornear ', ua: ' to bake' },
  { es: 'asar ', ua: '  to grill / roast' },
  { es: 'saltear ', ua: ' to saute' },
  { es: 'preparar ', ua: ' to prepare' },
  { es: 'descongelar ', ua: ' to defrost' },
  { es: 'quemar ', ua: '  to burn' },
  { es: 'tostar ', ua: '  to toast' },
  { es: 'derretir ', ua: ' to melt' },
  { es: 'rodajear ', ua: '  to slice' },
  { es: 'calentar ', ua: '  to warm up / heat' },
  { es: 'rellenar ', ua: '  to fill / stuff' },
  { es: 'lavar ', ua: '  to wash' },
  { es: 'limpiar ', ua: '  to clean' },
  { es: 'desayunar ', ua: ' to have breakfast' },
  { es: 'cenar ', ua: ' to have dinner' },
  { es: 'la puerta ', ua: '  the door' },
  { es: 'el armario ', ua: ' the wardrobe' },
  { es: 'la estantería ', ua: ' the shelf' },
  { es: 'la ventana ', ua: ' the window' },
  { es: 'las cortinas ', ua: '  the curtains' },
  { es: 'el escritorio ', ua: '  the desk' },
  { es: 'el ordenador ', ua: '  the computer' },
  { es: 'la cama ', ua: ' the bed' },
  { es: 'el cojín ', ua: ' the pillow' },
  { es: 'el edredón ', ua: ' the quilt' },
  { es: 'las sábanas ', ua: ' the bedding' },
  { es: 'la almohada ', ua: ' the pillowcase' },
  { es: 'la lámpara ', ua: ' the lamp' },
  { es: 'la mesilla de noche ', ua: ' the night table or nightstand' },
  { es: 'el espejo ', ua: ' the mirror' },
  { es: 'el cuadro ', ua: ' the painting' },
  { es: 'la puerta ', ua: ' the door' },
  { es: 'el armario ', ua: '  the wardrobe' },
  { es: 'la estantería ', ua: '  the shelf' },
  { es: 'la ventana ', ua: '  the window' },
  { es: 'las cortinas ', ua: ' the curtains' },
  { es: 'la mesa ', ua: '  the table' },
  { es: 'la silla ', ua: ' the chair' },
  { es: 'el sillón ', ua: ' armchair' },
  { es: 'la alfombra ', ua: ' the carpet or rug' },
  { es: 'la lámpara ', ua: ' the lamp' },
  { es: 'la planta ', ua: ' the plant' },
  { es: 'las flores ', ua: ' the flowers' },
  { es: 'la chimenea ', ua: ' the chimney' },
  { es: 'el suelo ', ua: ' the ground' },
  { es: 'el techo ', ua: ' the ceiling' },
  { es: 'dependiente/a ', ua: ' shop assistant' },
  { es: 'caja ', ua: ' checkout' },
  { es: 'rebajas ', ua: ' sales' },
  { es: 'ocasión ', ua: ' bargain' },
  { es: 'recibo ', ua: ' receipt' },
  { es: 'probadores ', ua: ' dressing room' },
  { es: 'tamaño ', ua: ' size' },
  { es: 'tienda de ropa ', ua: ' clothing store' },
  { es: 'zapatería ', ua: ' shoe store' },
  { es: 'librería ', ua: ' bookstore' },
  { es: 'almacén ', ua: ' department store' },
  { es: 'supermercado ', ua: ' supermarket' },
  { es: 'joyería ', ua: ' jeweler' },
  { es: 'juguetería ', ua: ' toy store' },
  { es: 'almacenero(a) ', ua: ' grocer' },
  { es: 'comerciante (a) ', ua: ' merchant' },
  { es: 'tendero(a) ', ua: ' shopkeeper' },
  { es: 'dependiente ', ua: ' clerk' },
  { es: 'cajero(a) ', ua: ' cashier' },
  { es: 'los cuidados de la salud ', ua: ' healthcare' },
  { es: 'el dentista ', ua: ' dentist' },
  { es: 'el doctor/a ', ua: ' doctor' },
  { es: 'el enfermero/a ', ua: ' nurse' },
  { es: 'el médico general ', ua: ' general practitioner' },
  { es: 'el médico de cabecera ', ua: ' general practitioner' },
  { es: 'el médico especialista ', ua: ' specialist' },
  { es: 'el/la nutricionista ', ua: ' nutritionist' },
  { es: 'el/la paciente ', ua: ' patient' },
  { es: 'el/la paramédico ', ua: ' paramedic' },
  { es: 'quiropráctico(a) ', ua: ' chiropractor' },
  { es: 'el/la pediatra ', ua: ' pediatrician' },
  { es: 'el psicólogo/a ', ua: ' psychologist' },
  { es: 'los primeros auxilios ', ua: ' first aid' },
  { es: 'la salud ', ua: ' health' },
  { es: 'la ambulancia ', ua: ' ambulance' },
  { es: 'la aseguradora ', ua: ' insurance carrier' },
  { es: 'el centro de salud ', ua: ' clinic' },
  { es: 'la clínica ', ua: ' clinic' },
  { es: 'la farmacia ', ua: ' drug store' },
  { es: 'droguería ', ua: ' drug store' },
  { es: 'el hospital ', ua: ' hospital' },
  { es: 'el pabellón ', ua: ' ward' },
  { es: 'la sala de espera ', ua: ' waiting room' },
  { es: 'la sala de operaciones ', ua: ' operating room' },
  { es: 'el sanatorio ', ua: ' sanatorium' },
  { es: 'la alergía ', ua: ' allergy' },
  { es: 'la asfixia ', ua: ' suffocation' },
  { es: 'el asma ', ua: ' asthma' },
  { es: 'el ataque al corazón/paro cardiaco ', ua: ' heart attack' },
  { es: 'el calambre ', ua: ' muscle cramp' },
  { es: 'el cancer ', ua: ' cancer' },
  { es: 'el chinchón', ua: ' head bump' },
  { es: 'el corte ', ua: ' cut' },
  { es: 'la deshidratación ', ua: ' dehydration' },
  { es: 'la diabetes ', ua: ' diabetes' },
  { es: 'la diarrea ', ua: ' diarrhea' },
  { es: 'el dolor ', ua: ' ache/pain' },
  { es: 'el dolor de cabeza ', ua: ' headache' },
  { es: 'el dolor de garganta ', ua: ' sore throat' },
  { es: 'el dolor de estómago ', ua: ' stomach ache' },
  { es: 'el dolor de diente ', ua: ' toothache' },
  { es: 'la enfermedad ', ua: ' disease' },
  { es: 'la enfermedad cardiaca ', ua: ' heart disease' },
  { es: 'la enfermedad infecciosa ', ua: ' infectious disease' },
  { es: 'los escalofríos', ua: ' shaking chills' },
  { es: 'la fractura ', ua: ' fracture' },
  { es: 'la fiebre ', ua: ' fever' },
  { es: 'la gripe ', ua: ' flu' },
  { es: 'la herida ', ua: ' wound' },
  { es: 'la hipotermia ', ua: ' hypothermia' },
  { es: 'la infección ', ua: ' infection' },
  { es: 'el malestar ', ua: ' discomfort' },
  { es: 'el morete/moretón ', ua: ' bruise' },
  { es: 'la náusea ', ua: ' nausea' },
  { es: 'el raspón ', ua: ' graze' },
  { es: 'el resfriado ', ua: ' cold' },
  { es: 'el sangrado ', ua: ' bleeding' },
  { es: 'la tos ', ua: ' cough' },
  { es: 'el virus ', ua: ' virus' },
  { es: 'el vomito ', ua: ' vomit' }
]

document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Add a click event on each of them
    $navbarBurgers.forEach(el => {
        el.addEventListener('click', () => {

            // Get the target from the "data-target" attribute
            const target = el.dataset.target;
            const $target = document.getElementById(target);

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');

        });
    });
});
