export const wordPairsVerbos = [
  { es: 'abrir', ua: 'відкривати', en: 'to open' },
  { es: 'acabar', ua: 'закінчувати', en: 'to finish' },
  { es: 'acompañar', ua: 'проводити, супроводжувати', en: 'to accompany' },
  {
    es: 'agradecer',
    ua: 'подякувати, бути вдячним',
    en: 'to thank, be grateful',
  },
  { es: 'almorzar', ua: 'обідати', en: 'to have lunch' },
  { es: 'aparecer', ua: 'з`явитися', en: 'to appear' },
  { es: 'aprender', ua: 'вчити', en: 'to learn' },
  { es: 'aterrizar', ua: 'приземлятися', en: 'to land' },
  { es: 'ayudar', ua: 'допомагати', en: 'to help' },
  { es: 'bailar', ua: 'танцювати', en: 'to dance' },
  { es: 'bajar', ua: 'спускатися', en: 'to step down' },
  { es: 'bañar', ua: 'купати', en: 'to bath' },
  { es: 'bañarse', ua: 'купатися', en: 'to take a bath' },
  { es: 'beber', ua: 'пити', en: 'to drink' },
  { es: 'caber', ua: 'вміщатись', en: 'to fit' },
  { es: 'caer', ua: 'падати', en: 'to fall' },
  { es: 'calmar ', ua: 'заспокоювати', en: 'to calm' },
  { es: 'cantar', ua: 'співати', en: 'to sing' },
  { es: 'cocinar', ua: 'готувати', en: 'to cook' },
  { es: 'coger', ua: 'ловити, схопити', en: 'to catch, grab' },
  { es: 'comenzar', ua: 'починати', en: 'to begin' },
  { es: 'comer', ua: 'їсти', en: 'to eat' },
  { es: 'compartir', ua: 'ділити', en: 'to share' },
  { es: 'complacer', ua: 'годити, догоджати', en: 'to please' },
  { es: 'componer', ua: 'складати, зʼєднувати', en: 'to compose' },
  { es: 'comprar', ua: 'купувати', en: 'to buy' },
  { es: 'comprender', ua: 'розуміти', en: 'to understand' },
  { es: 'conducir', ua: 'курувати (авто)', en: 'to drive, lead' },
  { es: 'conoser', ua: 'знати, зайомитись', en: 'to know' },
  { es: 'contar', ua: 'казати', en: 'to tell' },
  { es: 'contener', ua: 'містити, включати в себе', en: 'to contain' },
  { es: 'contestar', ua: 'відповідати', en: 'to answer' },
  { es: 'convencer', ua: 'переконувати, вражати', en: 'to convince' },
  { es: 'conversar', ua: 'розмовляти, обговорювати', en: 'to talk' },
  { es: 'cooperar', ua: 'співпрацювати', en: 'to cooperate' },
  { es: 'correr', ua: 'бігти', en: 'to run' },
  { es: 'crecer', ua: 'рости', en: 'to grow' },
  { es: 'creer', ua: 'вірити', en: 'to believe' },
  { es: 'cubrir', ua: 'накривати', en: 'to cover' },
  { es: 'dar', ua: 'давати', en: 'to give' },
  { es: 'dar gritos', ua: 'кричати', en: 'to shout, scream' },
  { es: 'dar la hora', ua: 'відбивати годину', en: 'to strike the hour' },
  { es: 'dar un abrazo', ua: 'обіймати', en: 'to hug, embrace' },
  { es: 'deber', ua: 'бути зобовʼязаним', en: 'to have to ' },
  { es: 'decidir', ua: 'вирішувати', en: 'to decide' },
  { es: 'decir', ua: 'розповідати', en: 'to say' },
  { es: 'depender', ua: 'залежати', en: 'to depend' },
  { es: 'desayunar', ua: 'снідати', en: 'to have breakfast' },
  { es: 'descansar', ua: 'відпочівати', en: 'to rest' },
  { es: 'deshacer', ua: 'робити (в зворотньому напрямку)', en: 'to undo' },
  { es: 'despegar', ua: 'злітати (в літаку)', en: 'to take off' },
  { es: 'detener', ua: 'затримати', en: 'to detain' },
  { es: 'dibujar', ua: 'малювати', en: 'to draw' },
  { es: 'dirigir', ua: 'направляти', en: 'to direct' },
  { es: 'discutir', ua: 'обговорити, дискутувати', en: 'to discuss' },
  { es: 'disponer', ua: 'організовувати, готуватися', en: 'to arrange' },
  { es: 'distinguir', ua: 'розрізняти', en: 'to distinguish' },
  { es: 'distraer', ua: 'відволікати', en: 'to distract' },
  { es: 'distraerse', ua: 'відволікатися', en: 'to get distracted' },
  { es: 'dormir', ua: 'спати', en: 'to sleep' },
  {
    es: 'ejercer',
    ua: 'практикувати (професію)',
    en: 'to practice (a profession)',
  },
  { es: 'elegir', ua: 'обирати', en: 'to choose' },
  { es: 'encoger', ua: 'стягуватися, зжиматися', en: 'to shrink' },
  { es: 'encontrar', ua: 'знаходити', en: 'to find' },
  { es: 'encontrarse', ua: 'зустрічатися', en: 'to meet' },
  { es: 'enrojecer', ua: 'червоніти (соромитись)', en: 'to blush' },
  { es: 'enseñar', ua: 'викладати, навчати', en: 'to teach' },
  { es: 'escoger', ua: 'вибирати', en: 'to choose' },
  { es: 'escribir', ua: 'писати', en: 'to write' },
  { es: 'escuchar', ua: 'слухати', en: 'to listen' },
  { es: 'establecer', ua: 'встановити', en: 'to establish' },
  { es: 'estar', ua: 'бути (фізично десь, в певному стані)', en: 'to be' },
  { es: 'estudiar', ua: 'вчити', en: 'to study' },
  { es: 'exigir', ua: 'вимагати', en: 'to demand' },
  { es: 'extinguir', ua: 'гасити (вогонь), знищувати', en: 'to extinguish' },
  { es: 'fingir', ua: 'прикидатися', en: 'to pretend' },
  { es: 'ganar', ua: 'вигравати, заробляти', en: 'to gain' },
  { es: 'gustar', ua: 'подобатись', en: 'to like' },
  { es: 'haber neblina', ua: 'бути туманно', en: 'to be foggy' },
  { es: 'haber sol', ua: 'бути сонячно', en: 'to be sunny' },
  { es: 'hablar', ua: 'розмовляти', en: 'to talk' },
  { es: 'hacer', ua: 'робити', en: 'to do' },
  { es: 'hacer calor ', ua: 'бути гаряче', en: 'to be hot' },
  {
    es: 'hacer caso a',
    ua: 'помітити, звернути увагу (на)',
    en: 'to notice, pay attention (to)',
  },
  { es: 'hacer daño', ua: 'шкодити, пошкодити', en: 'to harm, damage' },
  { es: 'hacer el papel de', ua: 'грати роль', en: 'to play the role of' },
  { es: 'hacer fresco', ua: 'бути холодно', en: 'to be cool' },
  { es: 'hacer un viaje', ua: 'здійснити поїздку', en: 'to take a trip' },
  { es: 'hacer una visita', ua: 'відвідати', en: 'to pay a visit' },
  { es: 'hacer viento', ua: 'бути вітряно', en: 'to be windy' },
  {
    es: 'hay que + infinitivo',
    ua: 'бути необхідно',
    en: 'to be necessary (to express obligation)',
  },
  { es: 'ingresar', ua: 'поповнювати', en: 'to deposit' },
  { es: 'interesar', ua: 'цікавитись', en: 'to interest' },
  { es: 'interpretar un papel', ua: 'грати роль', en: 'to play a role' },
  { es: 'ir', ua: 'йти', en: 'to go' },
  { es: 'jugar', ua: 'грати в ігри', en: 'to play' },
  { es: 'lavar', ua: 'мити', en: 'to wash' },
  { es: 'leer', ua: 'читати', en: 'to read' },
  { es: 'limpiar', ua: 'чистити', en: 'to clean' },
  { es: 'llamar', ua: 'називати, телефонувати', en: 'to call' },
  { es: 'llegar', ua: 'прибувати', en: 'to arrive, to reach, to get to' },
  {
    es: 'llevar',
    ua: 'нести, носити (одяг)',
    en: 'to take, to carry, to wear',
  },
  { es: 'mantener', ua: 'підтримувати (форму, стан)', en: 'to maintain' },
  { es: 'merecer', ua: 'заслуговувати, бути вартим', en: 'to deserve' },
  {
    es: 'meriendar',
    ua: 'перекушувати (між обідом і вечерею)',
    en: 'to snack',
  },
  { es: 'mirar', ua: 'дивитись', en: 'to look' },
  { es: 'nadar', ua: 'плавати', en: 'to swim' },
  { es: 'necesitar', ua: 'потребувати', en: 'to need' },
  { es: 'obtener', ua: 'отримувати, вигравати', en: 'to obtain' },
  { es: 'ofrecer', ua: 'пропонувати', en: 'to offer' },
  { es: 'oír ', ua: 'чути', en: 'to hear' },
  { es: 'olvidar', ua: 'забувати', en: 'to forget' },
  { es: 'padecer', ua: 'страждати (від хвороби)', en: 'to suffer' },
  { es: 'pagar ', ua: 'платити', en: 'to pay' },
  { es: 'pasar', ua: 'проводити час, траплятись', en: 'to pass' },
  { es: 'pasear', ua: 'гуляти, прогулюватися', en: 'to go for a walk' },
  { es: 'pensar', ua: 'думати', en: 'to think' },
  { es: 'perdir', ua: 'втрачати, губити', en: 'to lose' },
  { es: 'permanecer', ua: 'залишатися', en: 'to remain' },
  { es: 'pertenecer', ua: 'належати', en: 'to belong' },
  { es: 'poder', ua: 'могти, мати можливість', en: 'to can' },
  { es: 'poner', ua: 'класти', en: 'to put' },
  { es: 'preguntar', ua: 'запитувати', en: 'to ask' },
  { es: 'preparar', ua: 'готувати ', en: 'to prepare' },
  { es: 'probar', ua: 'пробувати', en: 'to prove' },
  { es: 'producir', ua: 'виробляти', en: 'to produce' },
  { es: 'prometer', ua: 'обіцяти', en: 'to promise, to pledge' },
  { es: 'proponer', ua: 'пропонувати', en: 'to propose' },
  { es: 'proteger', ua: 'захищати', en: 'to protect' },
  { es: 'querer', ua: 'хотіти, любити', en: 'to want, to love' },
  { es: 'recibir', ua: 'отримувати', en: 'to recieve' },
  { es: 'recoger', ua: 'підібрати', en: 'to pick up' },
  { es: 'reconocer', ua: 'впізнавати', en: 'to recognize' },
  { es: 'regalar', ua: 'дарувати', en: 'to give a present' },
  { es: 'rehacer', ua: 'переробляти', en: 'to remake' },
  { es: 'reír', ua: 'сміятися', en: 'to laugh' },
  { es: 'repartir', ua: 'розповсюджувати', en: 'to distribute' },
  { es: 'reponer', ua: 'замінювати', en: 'to replace' },
  { es: 'responder', ua: 'відповідати', en: 'to answer' },
  { es: 'retener', ua: 'зберегти, тримати', en: 'to retain' },
  { es: 'romper', ua: 'ламати, рвати', en: 'to break' },
  { es: 'saber', ua: 'знати', en: 'to know' },
  { es: 'sacar', ua: 'вийняти', en: 'to take out' },
  { es: 'salir', ua: 'залишати, покидати', en: 'to leave' },
  { es: 'ser', ua: 'бути', en: 'to be' },
  { es: 'ser amigos', ua: 'бути друзями, дружити', en: 'to be friends' },
  { es: 'solicitar', ua: 'запитувати,', en: 'to request, to ask for, to seek' },
  { es: 'sostener', ua: 'тримати', en: 'to hold, to sustain' },
  { es: 'subir', ua: 'піднятися, підніміться вгору', en: 'to climb, go up' },
  { es: 'sufrir', ua: 'страждати', en: 'to suffer' },
  { es: 'sumar', ua: 'додавати', en: 'to add (up)' },
  {
    es: 'suponer',
    ua: 'вгадувати, уявляти',
    en: 'to guess, to imagine, to suppose',
  },
  { es: 'temer', ua: 'боятись, тривожитись', en: 'to fear, to worry' },
  { es: 'tener', ua: 'мати', en: 'to have' },
  { es: 'tener + que + infinitive', ua: 'потрібно', en: 'must' },
  { es: 'tener frío', ua: 'бути холодно', en: 'to be cold' },
  { es: 'tener hambre', ua: 'бути голодним', en: 'to be hungry' },
  {
    es: 'tener la culpa (de)',
    ua: 'бути звинуваченим (у)',
    en: 'to be to blame (for)',
  },
  { es: 'tener lugar', ua: 'відбуватися', en: 'to take place' },
  { es: 'tener miedo', ua: 'боятись, мати страх', en: 'to be afraid' },
  { es: 'tener prisa', ua: 'поспішати', en: 'to be in a hurry' },
  { es: 'tener razón', ua: 'бути правим, мати рацію', en: 'to be right' },
  { es: 'tener sed', ua: 'бути спраглим', en: 'to be thirsty' },
  { es: 'tomar', ua: 'брати, мати', en: 'to take' },
  { es: 'torcer', ua: 'скручувати', en: 'to twist' },
  { es: 'trabajar', ua: 'працювати', en: 'to work' },
  { es: 'traducir', ua: 'перекладати', en: 'to translate' },
  { es: 'traer', ua: 'приносити, носити (з собою, на собі)', en: 'to bring' },
  { es: 'tranquilizar', ua: 'заспокоювати', en: 'to call down, to quiet' },
  {
    es: 'trasladar',
    ua: 'рухатись, переїзджати',
    en: 'to move, to translate, to transfer',
  },
  { es: 'valer', ua: 'коштувати, бути цінним', en: 'to cost, to be worth' },
  {
    es: 'vencer',
    ua: 'подолати',
    en: 'to overcome, to win, to beat, to defeat',
  },
  { es: 'vender', ua: 'продавати', en: 'to sell' },
  { es: 'venir', ua: 'приходити, приїзджати', en: 'to come' },
  { es: 'ver', ua: 'бачити', en: 'to see' },
  { es: 'viajar', ua: 'мандрувати', en: 'to travel' },
  { es: 'vivir', ua: 'жити', en: 'to live' },
]
